# Generated by Django 3.2.5 on 2023-03-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0001_initial'),
        ('dqa', '0002_auditteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditteam',
            name='dqa',
        ),
        migrations.AddField(
            model_name='auditteam',
            name='facility_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities'),
        ),
        migrations.AddField(
            model_name='auditteam',
            name='quarter_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period'),
        ),
    ]
