# Generated by Django 3.2.18 on 2023-03-23 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0003_auto_20230317_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataverification',
            name='indicator',
            field=models.CharField(choices=[('', 'Select indicator'), ('PrEP_New', 'PrEP_New'), ('Starting_TPT', 'Starting TPT'), ('GBV_Sexual violence', 'GBV_Sexual violence'), ('GBV_Emotional and /Physical Violence', 'GBV_Emotional and /Physical Violence'), ('Cervical Cancer Screening (Women on ART)', 'Cervical Cancer Screening (Women on ART)'), ('Total tested ', 'Total tested '), ('Number tested Positive aged <15 years', 'Number tested Positive aged <15 years'), ('Number tested Positive aged 15+ years', 'Number tested Positive aged 15+ years'), ('Known Positive at 1st ANC', 'Known Positive at 1st ANC'), ('Positive Results_ANC', 'Positive Results_ANC'), ('On HAART at 1st ANC', 'On HAART at 1st ANC'), ('Start HAART ANC', 'Start HAART ANC'), ('Infant ARV Prophyl_ANC', 'Infant ARV Prophyl_ANC'), ('Positive Results_L&D', 'Positive Results_L&D'), ('Start HAART_L&D', 'Start HAART_L&D'), ('Infant ARV Prophyl_L&D', 'Infant ARV Prophyl_L&D'), ('Positive Results_PNC<=6 weeks', 'Positive Results_PNC<=6 weeks'), ('Start HAART_PNC<= 6 weeks', 'Start HAART_PNC<= 6 weeks'), ('Infant ARV Prophyl_PNC<= 6 weeks', 'Infant ARV Prophyl_PNC<= 6 weeks'), ('Under 15yrs Starting on ART', 'Under 15yrs Starting on ART'), ('Above 15yrs Starting on ART ', 'Above 15yrs Starting on ART '), ('New & Relapse TB_Cases', 'New & Relapse TB_Cases'), ('Currently on ART <15Years', 'Currently on ART <15Years'), ('Currently on ART 15+ years', 'Currently on ART 15+ years'), ('TX_ML', 'TX_ML'), ('RTT', 'RTT'), ('TB_PREV', 'TB_PREV')], max_length=250),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='indicator',
            field=models.CharField(choices=[('PrEP_New', 'PrEP_New'), ('Starting_TPT', 'Starting TPT'), ('GBV_Sexual violence', 'GBV_Sexual violence'), ('GBV_Emotional and /Physical Violence', 'GBV_Emotional and /Physical Violence'), ('Cervical Cancer Screening (Women on ART)', 'Cervical Cancer Screening (Women on ART)'), ('Total tested ', 'Total tested '), ('Number tested Positive aged <15 years', 'Number tested Positive aged <15 years'), ('Number tested Positive aged 15+ years', 'Number tested Positive aged 15+ years'), ('Number tested Positive _Total', 'Number tested Positive _Total'), ('Known Positive at 1st ANC', 'Known Positive at 1st ANC'), ('Positive Results_ANC', 'Positive Results_ANC'), ('On HAART at 1st ANC', 'On HAART at 1st ANC'), ('Start HAART ANC', 'Start HAART ANC'), ('Infant ARV Prophyl_ANC', 'Infant ARV Prophyl_ANC'), ('Positive Results_L&D', 'Positive Results_L&D'), ('Start HAART_L&D', 'Start HAART_L&D'), ('Infant ARV Prophyl_L&D', 'Infant ARV Prophyl_L&D'), ('Positive Results_PNC<=6 weeks', 'Positive Results_PNC<=6 weeks'), ('Start HAART_PNC<= 6 weeks', 'Start HAART_PNC<= 6 weeks'), ('Infant ARV Prophyl_PNC<= 6 weeks', 'Infant ARV Prophyl_PNC<= 6 weeks'), ('Total Positive (PMTCT)', 'Total Positive (PMTCT)'), ('Maternal HAART Total ', 'Maternal HAART Total '), ('Total Infant prophylaxis', 'Total Infant prophylaxis'), ('Under 15yrs Starting on ART', 'Under 15yrs Starting on ART'), ('Above 15yrs Starting on ART ', 'Above 15yrs Starting on ART '), ('Number of adults and children starting ART', 'Number of adults and children starting ART'), ('New & Relapse TB_Cases', 'New & Relapse TB_Cases'), ('Currently on ART <15Years', 'Currently on ART <15Years'), ('Currently on ART 15+ years', 'Currently on ART 15+ years'), ('Number of adults and children Currently on ART', 'Number of adults and children Currently on ART'), ('TX_ML', 'TX_ML'), ('RTT', 'RTT'), ('TB_PREV', 'TB_PREV')], max_length=250),
        ),
        migrations.CreateModel(
            name='KhisPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mfl_code', models.IntegerField()),
                ('facility', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('tst_p', models.IntegerField()),
                ('tst_a', models.IntegerField()),
                ('tst_t', models.IntegerField()),
                ('tst_pos_p', models.IntegerField()),
                ('tst_pos_a', models.IntegerField()),
                ('tst_pos_t', models.IntegerField()),
                ('tx_new_p', models.IntegerField()),
                ('tx_new_a', models.IntegerField()),
                ('tx_new_t', models.IntegerField()),
                ('tx_curr_p', models.IntegerField()),
                ('tx_curr_a', models.IntegerField()),
                ('tx_curr_t', models.IntegerField()),
                ('pmtct_stat_d', models.IntegerField()),
                ('pmtct_stat_n', models.IntegerField()),
                ('pmtct_pos', models.IntegerField()),
                ('pmtct_arv', models.IntegerField()),
                ('pmtct_inf_arv', models.IntegerField()),
                ('pmtct_eid', models.IntegerField()),
                ('hei_pos', models.IntegerField()),
                ('hei_pos_art', models.IntegerField()),
                ('prep_new', models.IntegerField()),
                ('gbv_sexual', models.IntegerField()),
                ('infant_arv_prophyl_anc', models.IntegerField()),
                ('infant_arv_prophyl_l_d', models.IntegerField()),
                ('infant_arv_prophyl_lt8wks_pnc', models.IntegerField()),
                ('haart_l_d', models.IntegerField()),
                ('pos_results_pnc_lt6wks', models.IntegerField()),
                ('start_haart_pnc_lt6wks', models.IntegerField()),
                ('kp_anc', models.IntegerField()),
                ('new_pos_anc', models.IntegerField()),
                ('on_haart_anc', models.IntegerField()),
                ('new_on_haart_anc', models.IntegerField()),
                ('pos_l_d', models.IntegerField()),
                ('pos_pnc', models.IntegerField()),
                ('cx_ca', models.IntegerField()),
                ('tb_stat_d', models.IntegerField()),
                ('ipt', models.IntegerField()),
                ('anc_initial_test', models.IntegerField()),
                ('first_anc_visits', models.IntegerField()),
                ('quarter_year', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'unique_together': {('mfl_code', 'month')},
            },
        ),
    ]
