# Generated by Django 3.2.18 on 2023-03-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0004_auto_20230323_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khisperformance',
            name='hei_pos',
        ),
        migrations.RemoveField(
            model_name='khisperformance',
            name='hei_pos_art',
        ),
        migrations.RemoveField(
            model_name='khisperformance',
            name='pmtct_eid',
        ),
    ]
