# Generated by Django 3.2.18 on 2023-03-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0005_auto_20230323_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverification',
            name='field_10',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='field_11',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='field_9',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='total_khis',
        ),
    ]
