# Generated by Django 3.2.18 on 2023-03-24 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0006_auto_20230324_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateButtonSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hide_button_time', models.TimeField()),
            ],
        ),
    ]
