# Generated by Django 3.2.18 on 2023-03-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0008_auto_20230326_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khisperformance',
            name='tb_prev_n',
        ),
        migrations.RemoveField(
            model_name='khisperformance',
            name='tx_ml',
        ),
        migrations.RemoveField(
            model_name='khisperformance',
            name='tx_rtt',
        ),
    ]
