# Generated by Django 3.2.18 on 2023-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0009_auto_20230326_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='fyjperformance',
            name='tb_prev_n',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fyjperformance',
            name='tx_ml',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fyjperformance',
            name='tx_rtt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
