# Generated by Django 3.2.18 on 2023-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0011_auto_20230327_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatebuttonsettings',
            name='days_to_keep_update_button_enabled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='updatebuttonsettings',
            name='disable_all_dqa_update_buttons',
            field=models.BooleanField(default=False),
        ),
    ]
