# Generated by Django 3.2.18 on 2023-04-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0012_auto_20230330_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dqaworkplan',
            options={'ordering': ['facility_name']},
        ),
        migrations.AlterModelOptions(
            name='systemassessment',
            options={'ordering': ['facility_name']},
        ),
    ]
