# Generated by Django 3.2.19 on 2023-08-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0013_auto_20230420_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fyjperformance',
            options={'ordering': ['facility']},
        ),
        migrations.AlterModelOptions(
            name='khisperformance',
            options={'ordering': ['facility']},
        ),
    ]
