# Generated by Django 3.2.25 on 2024-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0017_auto_20240605_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretreatment',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caretreatment',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cqi',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cqi',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gbv',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gbv',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hts',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hts',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prep',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prep',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tb',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmmc',
            name='denominator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vmmc',
            name='numerator_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
