# Generated by Django 3.2.25 on 2024-06-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0010_auto_20240518_0542'),
        ('dqa', '0020_auto_20240605_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretreatment',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='caretreatment',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='cqi',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='gbv',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='gbv',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='hts',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='hts',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='prep',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='prep',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='tb',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='tb',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
        migrations.AddField(
            model_name='vmmc',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties'),
        ),
        migrations.AddField(
            model_name='vmmc',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
    ]
