# Generated by Django 3.2.25 on 2024-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0022_auto_20240623_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqaworkplan',
            name='program_areas_reviewed',
            field=models.CharField(choices=[('HTS/PREVENTION/PMTCT', 'HTS/PREVENTION/PMTCT'), ('CHART ABSTRACTION', 'CHART ABSTRACTION'), ('M&E SYSTEMS', 'M&E SYSTEMS'), ('Data Management Systems', 'Data Management Systems'), ('Service Quality Assessment', 'Service Quality Assessment (SQA)')], max_length=255),
        ),
    ]
