# Generated by Django 3.2.19 on 2023-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='datacollectionreportingmanagement',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A (0)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataqualitysystems',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A (0)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A (0)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subcounties',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
