# Generated by Django 3.2.19 on 2023-08-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0002_auto_20230824_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='subcounties',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
