# Generated by Django 3.2.19 on 2023-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0003_auto_20230824_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacollectionreportingmanagement',
            options={'ordering': ['ward_name'], 'verbose_name_plural': 'Data Collection, Reporting and Management'},
        ),
        migrations.AlterModelOptions(
            name='dataqualitysystems',
            options={'ordering': ['ward_name'], 'verbose_name_plural': 'Data Quality Systems'},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['ward_name'], 'verbose_name_plural': 'Documentation'},
        ),
        migrations.AlterField(
            model_name='datacollectionreportingmanagement',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataqualitysystems',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Fully meets all requirements', 'Fully meets all requirements (5)'), ('Almost meets all requirements', 'Almost meets all requirements (4)'), ('Partially meets all requirements', 'Partially meets all requirements (3)'), ('Approaches basic requirements', 'Approaches basic requirements (2)'), ('Does not meet requirements', 'Does not meet requirements (1)'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='datacollectionreportingmanagement',
            unique_together={('quarter_year', 'description', 'ward_name')},
        ),
        migrations.AlterUniqueTogether(
            name='dataqualitysystems',
            unique_together={('quarter_year', 'description', 'ward_name')},
        ),
        migrations.AlterUniqueTogether(
            name='documentation',
            unique_together={('quarter_year', 'description', 'ward_name')},
        ),
    ]
