# Generated by Django 3.2.19 on 2023-08-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0009_auto_20230828_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_access_basic_sanitation_institutions_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_access_basic_sanitation_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_access_basic_water_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_access_safe_sanitation_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_access_safe_water_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_community_open_defecation_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataqualityassessment',
            name='number_trained_numeric',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
