# Generated by Django 3.2.19 on 2023-08-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0012_auto_20230830_2015'),
    ]

    operations = [
    ]
