# Generated by Django 3.2.19 on 2023-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0016_auto_20230830_2133'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP SCHEMA IF EXISTS your_app_name CASCADE",
        ),
    ]