# Generated by Django 3.2.19 on 2023-08-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0018_counties_datacollectionreportingmanagement_dataconcordance_dataqualityassessment_dataqualitysystems_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataconcordance',
            name='sub_county_name',
        ),
    ]
