# Generated by Django 3.2.19 on 2023-08-31 09:56

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wash_dqa', '0020_ward_ward_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JphesPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ward_code', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('number_trained', models.PositiveIntegerField(blank=True, null=True)),
                ('number_access_basic_water', models.PositiveIntegerField(blank=True, null=True)),
                ('number_access_safe_water', models.PositiveIntegerField(blank=True, null=True)),
                ('number_community_open_defecation', models.PositiveIntegerField(blank=True, null=True)),
                ('number_access_basic_sanitation', models.PositiveIntegerField(blank=True, null=True)),
                ('number_access_safe_sanitation', models.PositiveIntegerField(blank=True, null=True)),
                ('number_access_basic_sanitation_institutions', models.PositiveIntegerField(blank=True, null=True)),
                ('quarter_year', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ward_name'],
                'unique_together': {('ward_code', 'month')},
            },
        ),
    ]
