# Generated by Django 3.2.19 on 2023-09-01 07:10

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wash_dqa', '0021_jphesperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashAuditTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('carder', models.CharField(choices=[('County WASH Lead', 'County WASH Lead'), ('County WASH M/E', 'County WASH M/E'), ('FYJ WASH M/E', 'FYJ WASH M/E'), ('Program Officer', 'Program Officer'), ('WASH Coordinator', 'WASH Coordinator'), ('WASH Focal Person', 'WASH Focal Person'), ('WASH Mentor', 'WASH Mentor')], max_length=255)),
                ('organization', models.CharField(choices=[('FYJ', 'FYJ'), ('MOH', 'MOH')], max_length=255)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wash_dqa.period')),
                ('ward_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wash_dqa.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
