# Generated by Django 3.2.19 on 2023-09-01 10:44

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wash_dqa', '0022_washauditteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashDQAWorkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('dqa_date', models.DateField(blank=True, null=True)),
                ('individuals_conducting_dqa', models.TextField()),
                ('program_areas_reviewed', models.CharField(choices=[('Data Collection, Reporting and Management', 'Data Collection, Reporting and Management'), ('Data Quality Assessment', 'Data Quality Assessment'), ('Data Quality Systems', 'Data Quality Systems'), ('Data Verification', 'Data Verification'), ('Documentation', 'Documentation')], max_length=255)),
                ('strengths_identified', models.TextField()),
                ('gaps_identified', models.TextField()),
                ('recommendation', models.TextField()),
                ('percent_completed', models.IntegerField()),
                ('individuals_responsible', models.TextField()),
                ('due_complete_by', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('progress', models.FloatField(blank=True, null=True)),
                ('timeframe', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wash_dqa.period')),
                ('ward_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wash_dqa.ward')),
            ],
            options={
                'ordering': ['ward_name'],
            },
        ),
    ]
