# Generated by Django 3.2.19 on 2023-09-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0023_washdqaworkplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washdqaworkplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='washdqaworkplan',
            name='updated_at',
        ),
    ]
