# Generated by Django 3.2.19 on 2023-09-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wash_dqa', '0024_auto_20230901_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataconcordance',
            options={'ordering': ['ward_name', 'quarter_year']},
        ),
        migrations.AlterModelOptions(
            name='washauditteam',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'WASH Audit Team'},
        ),
        migrations.AlterModelOptions(
            name='washdqaworkplan',
            options={'ordering': ['ward_name'], 'verbose_name_plural': 'WASH DQA Work-plan'},
        ),
    ]
