# Generated by Django 3.2.5 on 2023-01-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'ordering': ['first_name']},
        ),
    ]
