# Generated by Django 3.2.5 on 2023-03-06 14:02

import apps.pmtct.models
import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cqi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateTimeField(validators=[apps.pmtct.models.validate_age])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ccc_no', models.BigIntegerField(unique=True, validators=[apps.pmtct.models.validate_ccc_no])),
                ('lmp', models.DateField(validators=[apps.pmtct.models.validate_lmp])),
                ('edd', models.DateTimeField()),
                ('gestation_by_age', models.IntegerField(blank=True, null=True)),
                ('date_enrolled_anc', models.DateTimeField()),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated/Divorced', 'Separated/DivorceSeparated'), ('Widowed', 'Widowed')], max_length=50, null=True)),
                ('partner_status', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('on_art', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('date_started_on_art', models.DateTimeField(blank=True, null=True)),
                ('update_status', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50, null=True)),
                ('update_status_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient details',
            },
        ),
        migrations.CreateModel(
            name='RiskCategorizationTrial',
            fields=[
                ('client_characteristics', models.CharField(choices=[('1. Is the client a newly HIV Positive (<3mnths)', '1. Is the client a newly HIV Positive (<3mnths)'), ('2. (a) Is the client an adolescent <19 years of age?', '2. (a) Is the client an adolescent <19 years of age?'), ('2. (b) Is the client an adolescent @ School>20yrs', '2. (b) Is the client an adolescent @ School>20yrs'), ('3. Is the client’s current VL >200 copies/ml', '3. Is the client’s current VL >200 copies/ml'), ('4. (a) Client has poor adherence : Delayed ART', '4. (a) Client has poor adherence : Delayed ART'), ('4. (b) Client has poor adherence : Missed >1 clinic appointments in the last scheduled 3 visits', '4. (b) Client has poor adherence : Missed >1 clinic appointments in the last scheduled 3 visits'), ('4. (c) Client has poor adherence : LTFU/IIT', '4. (c) Client has poor adherence : LTFU/IIT'), ('4. (d) Client has poor adherence : Declined ART', '4. (d) Client has poor adherence : Declined ART'), ('4. (e) Client has poor adherence : Missed ART doses', '4. (e) Client has poor adherence : Missed ART doses'), ('5. The client NOT disclosed to partner', '5. The client NOT disclosed to partner'), ('6. Does the client have any social family issues and/or severe poverty that could hinder optimal adherence or other related issues', '6. Does the client have any social family issues and/or severe poverty that could hinder optimal adherence or other related issues'), ('7. Is the client experiencing intimate partner violence or at risk of intimate partner violence?', '7. Is the client experiencing intimate partner violence or at risk of intimate partner violence?'), ('8. Does the client have active comorbidities? TB, DM, OIs, painful, swollen/cracked nipples, etc.', '8. Does the client have active comorbidities? TB, DM, OIs, painful, swollen/cracked nipples, etc.'), ('9. Is the client a lost to follow up/IIT who has returned to care', '9. Is the client a lost to follow up/IIT who has returned to care'), ('10. Client has malnourished HEI; SAM, MAM.', '10. Client has malnourished HEI; SAM, MAM.'), ('11. Does the client have a mental disability or require close care? Use PHQ9 to assess', '11. Does the client have a mental disability or require close care? Use PHQ9 to assess')], max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('early_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('mid_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('late_gestation', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('six_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('fourteen_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('six_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('nine_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('twelve_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('eighteen_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('twenty_four_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pmtct_mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails')),
            ],
            options={
                'verbose_name_plural': 'Risk Categorization trial',
                'unique_together': {('pmtct_mother', 'client_characteristics')},
            },
        ),
        migrations.CreateModel(
            name='RiskCategorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_characteristics', models.TextField()),
                ('baseline_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('early_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('mid_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('late_gestation', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('six_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('fourteen_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('six_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('nine_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('twelve_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('eighteen_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('twenty_four_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pmtct_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails')),
            ],
            options={
                'verbose_name_plural': 'Risk Categorization',
                'unique_together': {('pmtct_mother', 'client_characteristics')},
            },
        ),
    ]
