# Generated by Django 3.2.5 on 2023-03-03 07:17

import apps.pmtct.models
import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cqi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('date_of_birth', models.DateTimeField(validators=[apps.pmtct.models.validate_age])),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ccc_no', models.BigIntegerField(unique=True, validators=[apps.pmtct.models.validate_ccc_no])),
                ('lmp', models.DateField(validators=[apps.pmtct.models.validate_lmp])),
                ('edd', models.DateTimeField()),
                ('gestation_by_age', models.IntegerField(blank=True, null=True)),
                ('date_enrolled_anc', models.DateTimeField()),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated/Divorced', 'Separated/DivorceSeparated'), ('Widowed', 'Widowed')], max_length=50, null=True)),
                ('partner_status', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Unknown', 'Unknown')], max_length=50, null=True)),
                ('on_art', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('date_started_on_art', models.DateTimeField(blank=True, null=True)),
                ('update_status', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=50, null=True)),
                ('update_status_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patient details',
            },
        ),
        migrations.CreateModel(
            name='RiskCategorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_characteristics', models.TextField()),
                ('baseline_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('early_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('mid_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('late_gestation', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('six_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('fourteen_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('six_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('nine_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('twelve_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('eighteen_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('twenty_four_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pmtct_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails')),
            ],
            options={
                'verbose_name_plural': 'Risk Categorization',
            },
        ),
    ]
