# Generated by Django 3.2.5 on 2023-03-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmtct', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskCategorization',
        ),
    ]
