# Generated by Django 3.2.5 on 2023-03-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmtct', '0002_auto_20230303_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcategorization',
            name='pmtct_mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails', unique=True),
        ),
    ]
