# Generated by Django 3.2.5 on 2023-03-03 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pmtct', '0003_alter_riskcategorization_pmtct_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcategorization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='riskcategorization',
            name='pmtct_mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='riskcategorization',
            unique_together={('pmtct_mother', 'client_characteristics')},
        ),
    ]
