# Generated by Django 3.2.5 on 2023-03-03 17:33

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmtct', '0004_auto_20230303_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategorizationTrial',
            fields=[
                ('client_characteristics', models.CharField(choices=[('newly_hiv_positive', 'Is the client a newly HIV Positive (<3mnths)'), ('adolescent_less_than_19', 'Is the client an adolescent <19 years of age?'), ('adolescent_at_school_more_than_20', 'Is the client an adolescent @ School>20yrs'), ('current_vl_greater_than_200', 'Is the client’s current VL >200 copies/ml'), ('poor_adherence_delayed_art', 'Client has poor adherence : Delayed ART'), ('poor_adherence_missed_appointments', 'Client has poor adherence : Missed >1 clinic appointments in the last scheduled 3 visits'), ('poor_adherence_ltfu_iit', 'Client has poor adherence : LTFU/IIT'), ('poor_adherence_declined_art', 'Client has poor adherence : Declined ART'), ('poor_adherence_missed_art_doses', 'Client has poor adherence : Missed ART doses'), ('not_disclosed_to_partner', 'The client NOT disclosed to partner'), ('social_family_issues', 'Does the client have any social family issues and/or severe poverty that could hinder optimal adherence or other related issues'), ('intimate_partner_violence', 'Is the client experiencing intimate partner violence or at risk of intimate partner violence?'), ('active_comorbidities', 'Does the client have active comorbidities? TB, DM, OIs, painful, swollen/cracked nipples, etc.'), ('lost_to_follow_up', 'Is the client a lost to follow up/IIT who has returned to care'), ('malnourished_hei', 'Client has malnourished HEI; SAM, MAM.'), ('mental_disability', 'Does the client have a mental disability or require close care? Use PHQ9 to assess')], max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('early_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('mid_anc', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('late_gestation', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('six_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('fourteen_weeks_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('six_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('nine_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('twelve_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('eighteen_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('twenty_four_month_assessment', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA'), ('-', '-')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pmtct_mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails')),
            ],
            options={
                'verbose_name_plural': 'Risk Categorization trial',
                'unique_together': {('pmtct_mother', 'client_characteristics')},
            },
        ),
    ]
