# Generated by Django 3.2.5 on 2023-03-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmtct', '0005_riskcategorizationtrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='pmtct_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pmtct.patientdetails'),
        ),
    ]
