# Generated by Django 3.2.5 on 2023-03-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtct', '0008_alter_riskcategorizationtrial_client_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='baseline_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='early_anc',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='eighteen_month_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='fourteen_weeks_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='late_gestation',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='mid_anc',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='nine_month_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='six_month_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='six_weeks_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='twelve_month_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategorizationtrial',
            name='twenty_four_month_assessment',
            field=models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('NA', 'NA')], max_length=50, null=True),
        ),
    ]
