# Generated by Django 3.2.19 on 2023-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyjcarders',
            name='carder',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
