# Generated by Django 3.2.19 on 2023-06-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0002_alter_fyjcarders_carder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyjstaffdetails',
            name='hub',
            field=models.CharField(choices=[('All Hubs', 'All Hubs'), ('Hub 1 Nairobi', 'Hub 1 Nairobi'), ('Hub 2 Nairobi', 'Hub 2 Nairobi'), ('Hub 3 Nairobi', 'Hub 3 Nairobi'), ('Hub 1 Kajiado', 'Hub 1 Kajiado'), ('Hub 2 Kajiado', 'Hub 2 Kajiado'), ('Hub 3 Kajiado', 'Hub 3 Kajiado')], max_length=25),
        ),
    ]
