# Generated by Django 3.2.19 on 2023-06-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
        ('fyj_mentorship', '0004_facilitystaffcarders'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystaffcarders',
            name='facility_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities'),
        ),
    ]
