# Generated by Django 3.2.19 on 2023-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0005_facilitystaffcarders_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystaffcarders',
            name='staff_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
