# Generated by Django 3.2.19 on 2023-06-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0006_facilitystaffcarders_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitystaffcarders',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='facilitystaffcarders',
            name='staff_name',
        ),
    ]
