# Generated by Django 3.2.19 on 2023-06-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
        ('fyj_mentorship', '0008_facilitystaffdetails'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facilitystaffdetails',
            unique_together={('staff_name', 'facility_name')},
        ),
    ]
