# Generated by Django 3.2.19 on 2023-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0012_introduction_quarter_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='comments',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
