# Generated by Django 3.2.19 on 2023-06-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0050_alter_workplan_pharmacy_records'),
        ('fyj_mentorship', '0017_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='facilitystaffcarders',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='facilitystaffdetails',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='followup',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='fyjcarders',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='identificationgaps',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='preparecoachingsession',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AddField(
            model_name='programareas',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
    ]
