# Generated by Django 3.2.19 on 2023-06-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0019_mentorshipworkplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipworkplan',
            name='follow_up_plan',
        ),
    ]
