# Generated by Django 3.2.19 on 2023-06-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0013_auto_20230420_1439'),
        ('fyj_mentorship', '0020_remove_mentorshipworkplan_follow_up_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='quarter_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period'),
        ),
    ]
