# Generated by Django 3.2.19 on 2023-06-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
        ('fyj_mentorship', '0021_mentorshipworkplan_quarter_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyjstaffdetails',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.hub'),
        ),
    ]
