# Generated by Django 3.2.19 on 2023-06-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0022_alter_fyjstaffdetails_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyjstaffdetails',
            name='hub',
            field=models.CharField(choices=[('All Hubs', 'All Hubs'), ('Hub 1 Nairobi', 'Hub 1 Nairobi'), ('Hub 2 Nairobi', 'Hub 2 Nairobi'), ('Hub 3 Nairobi', 'Hub 3 Nairobi'), ('Hub 1 Kajiado', 'Hub 1 Kajiado'), ('Hub 2 Kajiado', 'Hub 2 Kajiado'), ('Hub 3 Kajiado', 'Hub 3 Kajiado')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
