# Generated by Django 3.2.19 on 2023-06-21 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0023_alter_fyjstaffdetails_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingsession',
            name='program_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyj_mentorship.programareas'),
        ),
        migrations.AddField(
            model_name='followup',
            name='program_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyj_mentorship.programareas'),
        ),
        migrations.AddField(
            model_name='identificationgaps',
            name='program_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyj_mentorship.programareas'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='program_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyj_mentorship.programareas'),
        ),
        migrations.AddField(
            model_name='preparecoachingsession',
            name='program_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fyj_mentorship.programareas'),
        ),
    ]
