# Generated by Django 3.2.19 on 2023-06-22 07:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fyj_mentorship', '0025_auto_20230622_0747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fyjstaffdetails',
            unique_together={('name', 'carder')},
        ),
    ]
