# Generated by Django 3.2.19 on 2023-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyj_mentorship', '0026_alter_fyjstaffdetails_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorshipworkplan',
            name='follow_up',
        ),
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='gaps_identified',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='individuals_responsible',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='percent_completed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='recommendation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorshipworkplan',
            name='timeframe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
