# Generated by Django 3.2.25 on 2024-05-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['name'], 'verbose_name_plural': 'Apps_available'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'User feedback'},
        ),
    ]
