# Generated by Django 3.2.25 on 2024-05-14 06:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20240513_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_feedback',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
