# Generated by Django 3.2.25 on 2024-05-18 01:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_user_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
