# Generated by Django 3.2.19 on 2023-06-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd4testinglabs',
            options={'verbose_name_plural': 'CD4 Testing Laboratories'},
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='date_of_collection',
            field=models.DateTimeField(),
        ),
    ]
