# Generated by Django 3.2.19 on 2023-06-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0002_auto_20230613_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='date_of_testing',
            field=models.DateTimeField(),
        ),
    ]
