# Generated by Django 3.2.19 on 2023-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0003_alter_cd4traker_date_of_testing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd4traker',
            options={'ordering': ['-date_dispatched'], 'verbose_name_plural': 'CD4 count tracker'},
        ),
        migrations.AddField(
            model_name='cd4traker',
            name='record_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
