# Generated by Django 3.2.19 on 2023-06-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0004_auto_20230613_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd4traker',
            name='record_count',
        ),
    ]
