# Generated by Django 3.2.19 on 2023-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0006_cd4traker_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
