# Generated by Django 3.2.19 on 2023-06-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0007_alter_cd4traker_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=9, null=True),
        ),
    ]
