# Generated by Django 3.2.19 on 2023-06-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0008_cd4traker_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='testing_lab_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
