# Generated by Django 3.2.19 on 2023-06-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0009_alter_cd4testinglabs_testing_lab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
