# Generated by Django 3.2.19 on 2023-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0010_cd4traker_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
