# Generated by Django 3.2.19 on 2023-06-15 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0011_alter_cd4traker_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='date_sample_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
