# Generated by Django 3.2.19 on 2023-06-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0012_cd4traker_date_sample_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd4traker',
            name='comments',
        ),
    ]
