# Generated by Django 3.2.19 on 2023-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0013_remove_cd4traker_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='comments',
            field=models.CharField(blank=True, choices=[('Stock outs', 'Stock outs'), ('Others', 'Others')], max_length=11, null=True),
        ),
    ]
