# Generated by Django 3.2.19 on 2023-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0014_cd4traker_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='received_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=9, null=True),
        ),
    ]
