# Generated by Django 3.2.19 on 2023-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0015_cd4traker_received_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='received_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
