# Generated by Django 3.2.19 on 2023-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0016_alter_cd4traker_received_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='reason_for_rejection',
            field=models.CharField(choices=[('Clotted sample/ hemolysed sample', 'Clotted sample/ hemolysed sample'), ('Improper Collection Technique', 'Improper Collection Technique'), ('Insufficient Volume', 'Insufficient Volume'), ('Missing Sample ( Physical Sample Missing)', 'Missing Sample ( Physical Sample Missing)'), ('Others', 'Others'), ('Requisition & Sample Mismatch', 'Requisition & Sample Mismatch'), ('Sample Missing on Requisition Form', 'Sample Missing on Requisition Form')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
