# Generated by Django 3.2.19 on 2023-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0017_cd4traker_reason_for_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='reason_for_rejection',
            field=models.CharField(blank=True, choices=[('Clotted sample/ hemolysed sample', 'Clotted sample/ hemolysed sample'), ('Improper Collection Technique', 'Improper Collection Technique'), ('Insufficient Volume', 'Insufficient Volume'), ('Missing Sample ( Physical Sample Missing)', 'Missing Sample ( Physical Sample Missing)'), ('Others', 'Others'), ('Requisition & Sample Mismatch', 'Requisition & Sample Mismatch'), ('Sample Missing on Requisition Form', 'Sample Missing on Requisition Form')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
