# Generated by Django 3.2.19 on 2023-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0018_auto_20230615_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='date_of_testing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
