# Generated by Django 3.2.19 on 2023-06-15 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0019_alter_cd4traker_date_of_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)]),
        ),
    ]
