# Generated by Django 3.2.19 on 2023-06-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0023_alter_cd4traker_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cd4traker',
            unique_together=set(),
        ),
    ]
