# Generated by Django 3.2.19 on 2023-06-16 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
        ('labpulse', '0027_alter_cd4traker_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties'),
        ),
    ]
