# Generated by Django 3.2.19 on 2023-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0030_alter_cd4traker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='cd4_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cd4traker',
            name='tb_lam_results',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive')], max_length=9, null=True),
        ),
    ]
