# Generated by Django 3.2.19 on 2023-06-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0031_auto_20230619_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4testinglabs',
            name='mfl_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
