# Generated by Django 3.2.19 on 2023-06-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0033_alter_cd4testinglabs_mfl_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='mfl_code',
            field=models.IntegerField(max_length=255, unique=True),
        ),
    ]
