# Generated by Django 3.2.19 on 2023-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0035_auto_20230620_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd4testinglabs',
            options={'ordering': ['testing_lab_name'], 'verbose_name_plural': 'CD4 Testing Laboratories'},
        ),
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='mfl_code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
