# Generated by Django 3.2.19 on 2023-06-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0037_cd4traker_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='justification',
            field=models.CharField(blank=True, choices=[('Baseline', 'Baseline'), ('Clinical Failure', 'Clinical Failure'), ('No Data', 'No Data'), ('Others', 'Others'), ('Routine CD4', 'Routine CD4'), ('Single Drug Substitution', 'Single Drug Substitution')], max_length=50, null=True),
        ),
    ]
