# Generated by Django 3.2.19 on 2023-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0038_alter_cd4traker_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='date_tb_lam_results_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='justification',
            field=models.CharField(blank=True, choices=[('Baseline (Tx_new)', 'Baseline (Tx_new)'), ('Return to care > 3 months', 'Return to care > 3 months'), ('Treatment Failure', 'Treatment Failure')], max_length=50, null=True),
        ),
    ]
