# Generated by Django 3.2.19 on 2023-06-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0013_auto_20230420_1439'),
        ('labpulse', '0040_cd4traker_date_serum_crag_results_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPulseUpdateButtonSettings',
            fields=[
                ('updatebuttonsettings_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dqa.updatebuttonsettings')),
            ],
            bases=('dqa.updatebuttonsettings',),
        ),
    ]
