# Generated by Django 3.2.19 on 2023-07-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0041_labpulseupdatebuttonsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='date_dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
