# Generated by Django 3.2.19 on 2023-07-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0044_cd4traker_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='report_type',
            field=models.CharField(blank=True, default='Current', max_length=25, null=True),
        ),
    ]
