# Generated by Django 3.2.19 on 2023-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0045_alter_cd4traker_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='justification',
            field=models.CharField(blank=True, choices=[('Baseline (Tx_new)', 'Baseline (Tx_new)'), ('On Fluconazole maintenance or Dapsone prophylaxis', 'On Fluconazole maintenance or Dapsone prophylaxis'), ('Return to care > 3 months', 'Return to care > 3 months'), ('Treatment Failure', 'Treatment Failure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='reason_for_rejection',
            field=models.CharField(blank=True, choices=[('Clotted sample/ hemolysed sample', 'Clotted Sample/ Hemolysed sample'), ('Improper Collection Technique', 'Improper Collection Technique'), ('Insufficient Volume', 'Insufficient Volume'), ('Missing Sample ( Physical Sample Missing)', 'Missing Sample ( Physical Sample Missing)'), ('Others', 'Others'), ('Requisition & Sample Mismatch', 'Requisition & Sample Mismatch'), ('Sample Missing on Requisition Form', 'Sample Missing On Requisition Form')], max_length=50, null=True),
        ),
    ]
