# Generated by Django 3.2.19 on 2023-08-17 09:33

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cqi', '0004_facilities_fyj_facilities'),
        ('labpulse', '0046_auto_20230809_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('type_of_reagent', models.CharField(choices=[('CD4', 'CD4'), ('Serum CrAg', 'Serum CrAg'), ('TB LAM', 'TB LAM')], max_length=25)),
                ('number_received', models.IntegerField(blank=True, null=True)),
                ('date_commodity_received', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('received_from', models.CharField(choices=[('KEMSA', 'KEMSA'), ('Another Facility', 'Another Facility')], max_length=25)),
                ('negative_adjustment', models.IntegerField(blank=True, null=True)),
                ('positive_adjustment', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties')),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
