# Generated by Django 3.2.19 on 2023-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0047_commodities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodities',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
