# Generated by Django 3.2.19 on 2023-08-18 03:45

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0007_alter_facilities_fyj_facilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labpulse', '0048_alter_commodities_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='justification',
            field=models.CharField(blank=True, choices=[('Baseline (Tx_new)', 'Baseline (Tx_new)'), ('Drug Resistance Test', 'Drug Resistance Test'), ('On Fluconazole maintenance or Dapsone prophylaxis', 'On Fluconazole maintenance or Dapsone prophylaxis'), ('Return to care > 3 months', 'Return to care > 3 months'), ('Treatment Failure', 'Treatment Failure')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReagentStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('reagent_type', models.CharField(choices=[('CD4', 'CD4'), ('TB LAM', 'TB LAM'), ('Serum CrAg', 'Serum CrAg')], max_length=25)),
                ('received_from', models.CharField(choices=[('KEMSA', 'KEMSA'), ('Another Facility', 'Another Facility')], max_length=25)),
                ('beginning_balance', models.IntegerField(default=0)),
                ('quantity_received', models.IntegerField(default=0)),
                ('positive_adjustments', models.IntegerField(default=0)),
                ('quantity_used', models.IntegerField(default=0)),
                ('negative_adjustment', models.IntegerField(default=0)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_expired', models.IntegerField(default=0)),
                ('date_commodity_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
