# Generated by Django 3.2.19 on 2023-08-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0049_auto_20230818_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_used',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
