# Generated by Django 3.2.19 on 2023-08-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0050_alter_reagentstock_quantity_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentstock',
            name='beginning_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='negative_adjustment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='positive_adjustments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_expired',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_received',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
