# Generated by Django 3.2.19 on 2023-08-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0051_auto_20230818_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentstock',
            name='beginning_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='negative_adjustment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='positive_adjustments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_expired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reagentstock',
            name='quantity_used',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
