# Generated by Django 3.2.19 on 2023-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0052_auto_20230818_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='cd4_reagent_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cd4traker',
            name='serum_crag_reagent_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cd4traker',
            name='tb_lam_reagent_used',
            field=models.BooleanField(default=False),
        ),
    ]
