# Generated by Django 3.2.19 on 2023-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0053_auto_20230819_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reagentstock',
            options={'verbose_name_plural': 'Reagent stocks'},
        ),
        migrations.AddField(
            model_name='reagentstock',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
