# Generated by Django 3.2.19 on 2023-09-11 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0054_auto_20230819_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='age_unit',
            field=models.CharField(choices=[('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10),
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150)]),
        ),
    ]
