# Generated by Django 3.2.19 on 2023-09-11 16:20

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labpulse', '0055_auto_20230911_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodities',
            options={'ordering': ['facility_name', 'date_created'], 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='reagentstock',
            options={'ordering': ['facility_name', 'date_created', 'remaining_quantity'], 'verbose_name_plural': 'Reagent stocks'},
        ),
        migrations.AlterField(
            model_name='cd4traker',
            name='age_unit',
            field=models.CharField(choices=[('', 'Select ...'), ('years', 'Years'), ('months', 'Months'), ('days', 'Days')], default='years', max_length=10),
        ),
        migrations.CreateModel(
            name='EnableDisableCommodities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('allow_commodities_use', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
