# Generated by Django 3.2.19 on 2023-09-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0057_auto_20230911_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enabledisablecommodities',
            old_name='disable_commodities_use',
            new_name='use_commodities',
        ),
    ]
