# Generated by Django 3.2.22 on 2023-11-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0059_biochemistryresult_drtresults'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrtResults',
        ),
    ]
