# Generated by Django 3.2.22 on 2023-11-24 14:49

import crum
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cqi', '0007_alter_facilities_fyj_facilities'),
        ('labpulse', '0060_delete_drtresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrtResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('patient_id', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('result', models.FileField(upload_to='drt_results')),
                ('collection_date', models.DateTimeField()),
                ('drug', models.CharField(max_length=50)),
                ('drug_abbreviation', models.CharField(max_length=10)),
                ('resistance_level', models.CharField(max_length=250)),
                ('sequence_summary', models.CharField(max_length=10)),
                ('haart_class', models.CharField(max_length=50)),
                ('date_received', models.DateTimeField()),
                ('date_reported', models.DateTimeField()),
                ('date_test_perfomed', models.DateTimeField()),
                ('test_perfomed_by', models.CharField(max_length=50)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.counties')),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.sub_counties')),
            ],
            options={
                'ordering': ['patient_id', 'date_created'],
            },
        ),
    ]
