# Generated by Django 3.2.22 on 2023-11-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0064_alter_drtresults_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drtresults',
            name='county',
        ),
        migrations.RemoveField(
            model_name='drtresults',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='drtresults',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='drtresults',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='drtresults',
            name='result',
        ),
        migrations.RemoveField(
            model_name='drtresults',
            name='sub_county',
        ),
        migrations.DeleteModel(
            name='DrtPdfFile',
        ),
        migrations.DeleteModel(
            name='DrtResults',
        ),
    ]
