# Generated by Django 3.2.22 on 2023-11-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0066_drtpdffile_drtresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='drtresults',
            name='tat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
