# Generated by Django 3.2.22 on 2023-11-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0068_alter_drtresults_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drtpdffile',
            options={'verbose_name_plural': 'DRT PDF Results'},
        ),
        migrations.AlterModelOptions(
            name='drtresults',
            options={'ordering': ['patient_id', 'date_created'], 'verbose_name_plural': 'DRT Results'},
        ),
        migrations.AddField(
            model_name='biochemistryresult',
            name='performed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
