# Generated by Django 3.2.22 on 2023-12-16 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0069_auto_20231129_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drtresults',
            name='patient_id',
            field=models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
