# Generated by Django 3.2.22 on 2024-01-10 11:15

from django.db import migrations, models
from django.db.models import ExpressionWrapper, F, IntegerField
from django.db.models.functions import Extract


class Migration(migrations.Migration):
    def update_tat_days(apps, schema_editor):
        Cd4traker = apps.get_model('labpulse', 'Cd4traker')
        Cd4traker.objects.filter(date_dispatched__isnull=False).update(
            tat_days=ExpressionWrapper(
                Extract(F('date_dispatched') - F('date_of_collection'), 'day'),
                output_field=IntegerField()
            )
        )

    dependencies = [
        ('labpulse', '0071_drtprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='tat_days',
            field=models.IntegerField(default=None,blank=True, null=True),
        ),
        migrations.RunPython(update_tat_days),
    ]
