# Generated by Django 3.2.22 on 2024-01-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0074_auto_20240111_1837'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_facilit_693a85_idx',
        ),
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_sub_cou_04c7e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_county__b5a295_idx',
        ),
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_testing_98d774_idx',
        ),
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_created_2c5d13_idx',
        ),
        migrations.RemoveIndex(
            model_name='cd4traker',
            name='labpulse_cd_modifie_564465_idx',
        ),
    ]
