# Generated by Django 3.2.22 on 2024-01-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0075_auto_20240111_1840'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['facility_name'], name='labpulse_cd_facilit_693a85_idx'),
        ),
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['sub_county'], name='labpulse_cd_sub_cou_04c7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['county'], name='labpulse_cd_county__b5a295_idx'),
        ),
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['testing_laboratory'], name='labpulse_cd_testing_98d774_idx'),
        ),
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['created_by'], name='labpulse_cd_created_2c5d13_idx'),
        ),
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['modified_by'], name='labpulse_cd_modifie_564465_idx'),
        ),
    ]
