# Generated by Django 3.2.22 on 2024-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0076_auto_20240111_1844'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cd4traker',
            index=models.Index(fields=['date_dispatched'], name='labpulse_cd_date_di_6ff7b5_idx'),
        ),
    ]
