# Generated by Django 3.2.22 on 2024-02-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0077_cd4traker_labpulse_cd_date_di_6ff7b5_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biochemistryresult',
            unique_together={('patient_id', 'test', 'collection_date', 'result')},
        ),
        migrations.RemoveField(
            model_name='biochemistryresult',
            name='sample_id',
        ),
    ]
