# Generated by Django 3.2.22 on 2024-02-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0078_auto_20240221_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochemistryresult',
            name='age',
            field=models.FloatField(default=0),
        ),
    ]
