# Generated by Django 3.2.22 on 2024-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0080_auto_20240223_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='biochemistryresult',
            name='tat_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
