# Generated by Django 3.2.25 on 2024-07-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0082_histologypdffile_histologyresults'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='histologyresults',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='county',
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='result',
        ),
        migrations.RemoveField(
            model_name='histologyresults',
            name='sub_county',
        ),
        migrations.DeleteModel(
            name='HistologyPdfFile',
        ),
        migrations.DeleteModel(
            name='HistologyResults',
        ),
    ]
