# Generated by Django 3.2.25 on 2024-07-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0086_auto_20240729_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histologyresults',
            name='date_reported',
        ),
    ]
