# Generated by Django 3.2.25 on 2024-07-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0088_remove_histologyresults_date_test_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histologyresults',
            name='test_performed_by',
        ),
    ]
