# Generated by Django 3.2.25 on 2024-07-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0089_remove_histologyresults_test_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='histologyresults',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
