# Generated by Django 3.2.25 on 2024-10-23 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0091_auto_20241022_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagentstock',
            name='date_commodity_dispensed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='reagentstock',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('RECEIVING', 'Receiving'), ('DISPENSING', 'Dispensing')], help_text='Select whether you are receiving or dispensing commodities', max_length=25, null=True),
        ),
    ]
