# Generated by Django 3.2.25 on 2024-10-23 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0092_auto_20241023_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentstock',
            name='date_commodity_received',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
