# Generated by Django 3.2.25 on 2024-11-06 08:49

from django.db import migrations, models


def set_default_testing_type(apps, schema_editor):
    Cd4traker = apps.get_model('labpulse', 'Cd4traker')
    Cd4traker.objects.all().update(testing_type='All')


class Migration(migrations.Migration):
    dependencies = [
        ('labpulse', '0093_alter_reagentstock_date_commodity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd4traker',
            name='testing_type',
            field=models.CharField(
                choices=[('All', 'All'), ('TB LAM Only', 'TB LAM Only'), ('ScrAg Only', 'ScrAg Only'),
                         ('TB LAM & ScrAg', 'TB LAM & ScrAg')], default='All', max_length=20),
        ),
        migrations.RunPython(set_default_testing_type),
        migrations.AlterField(
            model_name='reagentstock',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('RECEIVING', 'Receiving'), ('DISPENSING', 'Issuing')],
                                   help_text='Select whether you are receiving or dispensing commodities',
                                   max_length=25, null=True),
        ),

    ]
