# Generated by Django 3.2.25 on 2024-11-08 15:27

from django.db import migrations, models


def set_default_lab_type(apps, schema_editor):
    Cd4traker = apps.get_model('labpulse', 'Cd4traker')
    Cd4traker.objects.all().update(lab_type='Testing Laboratory')


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0096_cd4traker_lab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd4traker',
            name='lab_type',
            field=models.CharField(default='Testing Laboratory', max_length=25),
        ), migrations.RunPython(set_default_lab_type),
    ]
