# Generated by Django 3.2.25 on 2024-12-13 09:39

from django.db import migrations
import uuid


def create_knh_lab_and_assign(apps, schema_editor):
    BiochemistryTestingLab = apps.get_model('labpulse', 'BiochemistryTestingLab')
    BiochemistryResult = apps.get_model('labpulse', 'BiochemistryResult')

    # Create KNH lab
    knh_lab, created = BiochemistryTestingLab.objects.get_or_create(
        testing_lab_name="KNH Lab",
        defaults={
            'id': uuid.uuid4(),
            'mfl_code': 13023
        }
    )

    # Assign KNH lab to all existing results
    BiochemistryResult.objects.update(testing_lab=knh_lab)


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0099_biochemistryresult_testing_lab'),
    ]

    operations = [
        migrations.RunPython(create_knh_lab_and_assign),
    ]
