# Generated by Django 3.2.25 on 2024-12-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labpulse', '0101_remove_testing_lab_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BiochemistryTestingLab',
        ),
    ]
