# Generated by Django 3.2.25 on 2024-12-19 05:07

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labpulse', '0102_delete_biochemistrytestinglab'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd4testinglabs',
            options={'verbose_name_plural': 'CD4 Testing Laboratories'},
        ),
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='mfl_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cd4testinglabs',
            name='testing_lab_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='BiochemistryTestingLab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('testing_lab_name', models.CharField(default='', max_length=255)),
                ('mfl_code', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Biochemistry testing Laboratories',
            },
        ),
    ]
