# Generated by Django 3.2.25 on 2024-12-19 05:26
import uuid

from django.db import migrations


def create_knh_lab_and_assign(apps, schema_editor):
    BiochemistryTestingLab = apps.get_model('labpulse', 'BiochemistryTestingLab')
    BiochemistryResult = apps.get_model('labpulse', 'BiochemistryResult')

    # Create KNH lab
    knh_lab, created = BiochemistryTestingLab.objects.get_or_create(
        testing_lab_name="KNH LAB",
        defaults={
            'id': uuid.uuid4(),
            'mfl_code': 13023
        }
    )

    # Assign KNH lab to all existing results
    BiochemistryResult.objects.update(testing_lab=knh_lab)
def reverse_lab_assignment(apps, schema_editor):
    BiochemistryResult = apps.get_model('labpulse', 'BiochemistryResult')
    BiochemistryResult.objects.update(testing_lab=None)


class Migration(migrations.Migration):
    dependencies = [
        ('labpulse', '0104_biochemistryresult_testing_lab'),
    ]

    operations = [
        migrations.RunPython(create_knh_lab_and_assign, reverse_code=reverse_lab_assignment),
    ]
