# Generated by Django 3.2.5 on 2023-02-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('month', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('Mar', 'Mar'), ('Apr', 'Apr'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'Jul'), ('Aug', 'Aug'), ('Sep', 'Sep'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec')], max_length=3)),
                ('field_1', models.IntegerField()),
                ('field_2', models.IntegerField()),
                ('field_3', models.IntegerField()),
                ('field_4', models.IntegerField()),
                ('field_5', models.IntegerField()),
                ('field_6', models.IntegerField()),
                ('field_7', models.IntegerField()),
                ('field_8', models.IntegerField()),
                ('field_9', models.IntegerField()),
                ('field_10', models.IntegerField()),
                ('field_11', models.IntegerField()),
                ('field_12', models.IntegerField()),
                ('field_13', models.IntegerField()),
            ],
        ),
    ]
