# Generated by Django 3.2.5 on 2023-02-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0004_auto_20230209_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverification',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='year',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Quarters',
        ),
    ]
