# Generated by Django 3.2.5 on 2023-02-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0006_period_quarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Quarters',
        ),
    ]
