# Generated by Django 3.2.5 on 2023-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0007_auto_20230209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='quarter',
            field=models.CharField(choices=[('Qtr1', 'Q1'), ('Qtr2', 'Q2'), ('Qtr3', 'Q3'), ('Qtr4', 'Q4')], max_length=4),
        ),
    ]
