# Generated by Django 3.2.5 on 2023-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0007_auto_20230214_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqaworkplan',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
