# Generated by Django 3.2.5 on 2023-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0009_auto_20230214_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqaworkplan',
            name='percent_completed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
