# Generated by Django 3.2.5 on 2023-02-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0010_dataverification_quarter_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['quarter_year'], 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterField(
            model_name='dataverification',
            name='quarter_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period'),
        ),
    ]
