# Generated by Django 3.2.5 on 2023-02-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rootcauseimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dqa', '0011_alter_dataverification_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('dropdown_option', models.CharField(choices=[('Yes', 'Yes - completely'), ('Partly', 'Partly'), ('No', 'No - not at all'), ('N/A', 'N/A')], max_length=50)),
                ('component', models.CharField(max_length=250)),
                ('auditor_note', models.CharField(max_length=250)),
                ('supporting_documentation_required', models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('dqa_date', models.DateField()),
                ('calculations', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
            ],
        ),
    ]
