# Generated by Django 3.2.5 on 2023-02-09 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0012_auto_20230209_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataverification',
            name='field_12',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='field_4',
        ),
        migrations.RemoveField(
            model_name='dataverification',
            name='field_8',
        ),
        migrations.AddField(
            model_name='dataverification',
            name='total_731moh',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
        migrations.AddField(
            model_name='dataverification',
            name='total_khis',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
        migrations.AddField(
            model_name='dataverification',
            name='total_source',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
