# Generated by Django 3.2.5 on 2023-02-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0012_systemassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemassessment',
            name='auditor_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='systemassessment',
            name='component',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='systemassessment',
            name='dqa_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemassessment',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes - completely'), ('Partly', 'Partly'), ('No', 'No - not at all'), ('N/A', 'N/A')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='systemassessment',
            name='supporting_documentation_required',
            field=models.CharField(blank=True, choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
