# Generated by Django 3.2.5 on 2023-02-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dqa', '0014_auto_20230209_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataverification',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.newuser'),
            preserve_default=False,
        ),
    ]
