# Generated by Django 3.2.5 on 2023-02-09 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0015_dataverification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataverification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 9, 11, 32, 28, 296104, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
