# Generated by Django 3.2.5 on 2023-01-03 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['county_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(max_length=250, unique=True)),
                ('mfl_code', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['facilities'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_updated', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project comments',
            },
        ),
        migrations.CreateModel(
            name='Qi_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('designation', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'qi managers',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='QI_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Care and TX clinic', 'Care and TX clinic'), ('TB clinic', 'TB clinic'), ('Laboratory', 'Laboratory'), ('PMTCT', 'PMTCT'), ('Pharmacy', 'Pharmacy'), ('Community', 'Community'), ('VMMC', 'VMMC'), ('Nutrition clinic', 'Nutrition clinic'), ('OPD', 'OPD'), ('IPD', 'IPD')], default=0, max_length=200, null=True)),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects',
            },
        ),
        migrations.CreateModel(
            name='Sub_counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_counties', models.CharField(max_length=250, unique=True)),
                ('counties', models.ManyToManyField(to='project.Counties')),
                ('facilities', models.ManyToManyField(to='project.Facilities')),
            ],
            options={
                'verbose_name_plural': 'sub-counties',
                'ordering': ['sub_counties'],
            },
        ),
        migrations.CreateModel(
            name='TestedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('tested_change', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=2000)),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('achievements', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sub_counties')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_sub_counties',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=250)),
                ('resource', models.FileField(upload_to='resources')),
                ('description', models.TextField(max_length=1000)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date_updated', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qi_team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('designation', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('choose_qi_team_member_level', models.CharField(choices=[('Facility QI team member', 'Facility QI team member'), ('Sub-county QI team member', 'Sub-county QI team member'), ('County QI team member', 'County QI team member'), ('Hub QI team member', 'Hub QI team member'), ('Program QI team member', 'Program QI team member')], max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
            ],
            options={
                'verbose_name_plural': 'qi team members',
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='qi_projects',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.sub_counties'),
        ),
        migrations.CreateModel(
            name='ProjectResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response_updated_date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectcomments')),
                ('response_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project responses',
            },
        ),
        migrations.AddField(
            model_name='projectcomments',
            name='qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
        migrations.CreateModel(
            name='Program_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_program',
            },
        ),
        migrations.CreateModel(
            name='Hub_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('hub', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_hub',
            },
        ),
        migrations.CreateModel(
            name='County_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_counties',
            },
        ),
        migrations.CreateModel(
            name='Close_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_status_reason', models.CharField(max_length=250)),
                ('measurement_status_date', models.DateTimeField(auto_now_add=True)),
                ('limitations', models.TextField()),
                ('conclusion', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
            options={
                'verbose_name_plural': 'close_project',
            },
        ),
        migrations.CreateModel(
            name='ArchiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_project', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
            options={
                'verbose_name_plural': 'archived projects',
            },
        ),
    ]
