# Generated by Django 3.2.5 on 2022-11-12 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QI_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Care and Treatment clinic', 'Care and Treatment clinic'), ('TB clinic', 'TB clinic'), ('Laboratory', 'Laboratory'), ('PMTCT', 'PMTCT'), ('Pharmacy', 'Pharmacy'), ('Community', 'Community'), ('VMMC', 'VMMC'), ('Nutrition clinic', 'Nutrition clinic'), ('OPD', 'OPD'), ('IPD', 'IPD')], max_length=200)),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('facility', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(max_length=250)),
                ('measurement_frequency', models.CharField(max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QI_Projects',
            },
        ),
        migrations.CreateModel(
            name='Close_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_status_reason', models.CharField(max_length=250)),
                ('measurement_status_date', models.DateTimeField(auto_now_add=True)),
                ('limitations', models.TextField()),
                ('conclusion', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
            options={
                'verbose_name_plural': 'close_project',
            },
        ),
    ]
