# Generated by Django 3.2.5 on 2022-12-17 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'counties',
                'ordering': ['county_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['department'],
            },
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(choices=[('Baricho Health Centre', 'Baricho Health Centre'), ('Difathas Health Centre', 'Difathas Health Centre'), ('Gathambi Dispensary', 'Gathambi Dispensary'), ('Gathigiriri Dispensary', 'Gathigiriri Dispensary'), ('Kabare Health Centre', 'Kabare Health Centre'), ('Kagumo Health Center', 'Kagumo Health Center'), ('Kandongu Dispensary', 'Kandongu Dispensary'), ('Kangaita Health Centre', 'Kangaita Health Centre'), ('Kangaru Dispensary (Kirinyaga)', 'Kangaru Dispensary (Kirinyaga)'), ('Kangu dispensary', 'Kangu dispensary'), ('Karumandi Health Center', 'Karumandi Health Center'), ('Kerugoya District Hospital', 'Kerugoya District Hospital'), ('Kiamutugu Health Centre', 'Kiamutugu Health Centre'), ('Kiangai Dispensary', 'Kiangai Dispensary'), ('Kianyaga Sub-District Hospital', 'Kianyaga Sub-District Hospital'), ('Kibirigwi Health Centre', 'Kibirigwi Health Centre'), ('Kimbimbi Sub-District Hospital', 'Kimbimbi Sub-District Hospital'), ('Kiumbu Health Centre', 'Kiumbu Health Centre'), ('Kutus Dispensary', 'Kutus Dispensary'), ('Mt Kenya (ACK) Hospital', 'Mt Kenya (ACK) Hospital'), ('Murinduko Health Centre', 'Murinduko Health Centre'), ('Mutithi Health Centre', 'Mutithi Health Centre'), ('Kiaragana dispensary', 'Kiaragana dispensary'), ('Gatwe dispensary', 'Gatwe dispensary'), ('Njegas Dispensary', 'Njegas Dispensary'), ('Rukanga Dispensary', 'Rukanga Dispensary'), ('Sagana Sub-District Hospital', 'Sagana Sub-District Hospital'), ('Thiba Health Centre', 'Thiba Health Centre'), ('Ucheru Community Health Centre', 'Ucheru Community Health Centre'), ('Anmer Disp', 'Anmer Disp'), ('Betacare Hospital', 'Betacare Hospital'), ('Cianda Dispensary', 'Cianda Dispensary'), ('Gachege dispensary', 'Gachege dispensary'), ('Gachororo Health Centre', 'Gachororo Health Centre'), ('Gakoe Health centre', 'Gakoe Health centre'), ('Gathanga Health centre', 'Gathanga Health centre'), ('Gatundu level 4 Hospital', 'Gatundu level 4 Hospital'), ('Gichuru Health centre', 'Gichuru Health centre'), ('Gitare Health Centre', 'Gitare Health Centre'), ('Githiga Health Centre', 'Githiga Health Centre'), ('GITHUNGURI HEALTH CENTRE', 'GITHUNGURI HEALTH CENTRE'), ('Githuguri Health centre (ruir)', 'Githuguri Health centre (ruir)'), ('Hamundia Health Centre', 'Hamundia Health Centre'), ('Igegania SubCounty Hospital', 'Igegania SubCounty Hospital'), ('Immaculate Heart of mary', 'Immaculate Heart of mary'), ('Jkuat Hospital', 'Jkuat Hospital'), ('Jujafarm Health Centre', 'Jujafarm Health Centre'), ('Kagaa Dispensary', 'Kagaa Dispensary'), ('Kagwe Health centre', 'Kagwe Health centre'), ('Kalimoni Mission hospital', 'Kalimoni Mission hospital'), ('Karatu Health Centre', 'Karatu Health Centre'), ('Karuri SCH', 'Karuri SCH'), ('Kiambu CRH', 'Kiambu CRH'), ('Kiandutu Health Centre', 'Kiandutu Health Centre'), ('Kigumo SCH', 'Kigumo SCH'), ('Kihara SCH', 'Kihara SCH'), ('langata Health centre', 'langata Health centre'), ('Lari L4 Hospital', 'Lari L4 Hospital'), ('Limuru Health centre', 'Limuru Health centre'), ('Lusigetti SCH', 'Lusigetti SCH'), ('Makongeni dispensary', 'Makongeni dispensary'), ('AIP Mangu Dispensary', 'AIP Mangu Dispensary'), ('Mary Help of the sick', 'Mary Help of the sick'), ('Miguta Health centre', 'Miguta Health centre'), ('Munyu Health Centre', 'Munyu Health Centre'), ('Ndeiya Health centre', 'Ndeiya Health centre'), ('Ngenda Health centre', 'Ngenda Health centre'), ('Ngewa Health centre', 'Ngewa Health centre'), ('Ngoliba Health Centre', 'Ngoliba Health Centre'), ('Ngorongo Health Centre', 'Ngorongo Health Centre'), ('Nyathuna SCH', 'Nyathuna SCH'), ('Ruiru sub county Hospital', 'Ruiru sub county Hospital'), ('St.Mulumba Mission Hospital', 'St.Mulumba Mission Hospital'), ('Thika level 5 Hospital', 'Thika level 5 Hospital'), ('Thika Nursing Home', 'Thika Nursing Home'), ('Tigoni L4 Hospital', 'Tigoni L4 Hospital'), ('Uthiru Health centre', 'Uthiru Health centre'), ('Wangige SCH', 'Wangige SCH')], max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['facilities'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_updated', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project comments',
            },
        ),
        migrations.CreateModel(
            name='Qi_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qi_manager_name', models.CharField(max_length=250)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'qi managers',
                'ordering': ['qi_manager_name'],
            },
        ),
        migrations.CreateModel(
            name='QI_Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('Care and TX clinic', 'Care and TX clinic'), ('TB clinic', 'TB clinic'), ('Laboratory', 'Laboratory'), ('PMTCT', 'PMTCT'), ('Pharmacy', 'Pharmacy'), ('Community', 'Community'), ('VMMC', 'VMMC'), ('Nutrition clinic', 'Nutrition clinic'), ('OPD', 'OPD'), ('IPD', 'IPD')], default=0, max_length=200, null=True)),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('facility', models.CharField(choices=[('Baricho Health Centre', 'Baricho Health Centre'), ('Difathas Health Centre', 'Difathas Health Centre'), ('Gathambi Dispensary', 'Gathambi Dispensary'), ('Gathigiriri Dispensary', 'Gathigiriri Dispensary'), ('Kabare Health Centre', 'Kabare Health Centre'), ('Kagumo Health Center', 'Kagumo Health Center'), ('Kandongu Dispensary', 'Kandongu Dispensary'), ('Kangaita Health Centre', 'Kangaita Health Centre'), ('Kangaru Dispensary (Kirinyaga)', 'Kangaru Dispensary (Kirinyaga)'), ('Kangu dispensary', 'Kangu dispensary'), ('Karumandi Health Center', 'Karumandi Health Center'), ('Kerugoya District Hospital', 'Kerugoya District Hospital'), ('Kiamutugu Health Centre', 'Kiamutugu Health Centre'), ('Kiangai Dispensary', 'Kiangai Dispensary'), ('Kianyaga Sub-District Hospital', 'Kianyaga Sub-District Hospital'), ('Kibirigwi Health Centre', 'Kibirigwi Health Centre'), ('Kimbimbi Sub-District Hospital', 'Kimbimbi Sub-District Hospital'), ('Kiumbu Health Centre', 'Kiumbu Health Centre'), ('Kutus Dispensary', 'Kutus Dispensary'), ('Mt Kenya (ACK) Hospital', 'Mt Kenya (ACK) Hospital'), ('Murinduko Health Centre', 'Murinduko Health Centre'), ('Mutithi Health Centre', 'Mutithi Health Centre'), ('Kiaragana dispensary', 'Kiaragana dispensary'), ('Gatwe dispensary', 'Gatwe dispensary'), ('Njegas Dispensary', 'Njegas Dispensary'), ('Rukanga Dispensary', 'Rukanga Dispensary'), ('Sagana Sub-District Hospital', 'Sagana Sub-District Hospital'), ('Thiba Health Centre', 'Thiba Health Centre'), ('Ucheru Community Health Centre', 'Ucheru Community Health Centre'), ('Anmer Disp', 'Anmer Disp'), ('Betacare Hospital', 'Betacare Hospital'), ('Cianda Dispensary', 'Cianda Dispensary'), ('Gachege dispensary', 'Gachege dispensary'), ('Gachororo Health Centre', 'Gachororo Health Centre'), ('Gakoe Health centre', 'Gakoe Health centre'), ('Gathanga Health centre', 'Gathanga Health centre'), ('Gatundu level 4 Hospital', 'Gatundu level 4 Hospital'), ('Gichuru Health centre', 'Gichuru Health centre'), ('Gitare Health Centre', 'Gitare Health Centre'), ('Githiga Health Centre', 'Githiga Health Centre'), ('GITHUNGURI HEALTH CENTRE', 'GITHUNGURI HEALTH CENTRE'), ('Githuguri Health centre (ruir)', 'Githuguri Health centre (ruir)'), ('Hamundia Health Centre', 'Hamundia Health Centre'), ('Igegania SubCounty Hospital', 'Igegania SubCounty Hospital'), ('Immaculate Heart of mary', 'Immaculate Heart of mary'), ('Jkuat Hospital', 'Jkuat Hospital'), ('Jujafarm Health Centre', 'Jujafarm Health Centre'), ('Kagaa Dispensary', 'Kagaa Dispensary'), ('Kagwe Health centre', 'Kagwe Health centre'), ('Kalimoni Mission hospital', 'Kalimoni Mission hospital'), ('Karatu Health Centre', 'Karatu Health Centre'), ('Karuri SCH', 'Karuri SCH'), ('Kiambu CRH', 'Kiambu CRH'), ('Kiandutu Health Centre', 'Kiandutu Health Centre'), ('Kigumo SCH', 'Kigumo SCH'), ('Kihara SCH', 'Kihara SCH'), ('langata Health centre', 'langata Health centre'), ('Lari L4 Hospital', 'Lari L4 Hospital'), ('Limuru Health centre', 'Limuru Health centre'), ('Lusigetti SCH', 'Lusigetti SCH'), ('Makongeni dispensary', 'Makongeni dispensary'), ('AIP Mangu Dispensary', 'AIP Mangu Dispensary'), ('Mary Help of the sick', 'Mary Help of the sick'), ('Miguta Health centre', 'Miguta Health centre'), ('Munyu Health Centre', 'Munyu Health Centre'), ('Ndeiya Health centre', 'Ndeiya Health centre'), ('Ngenda Health centre', 'Ngenda Health centre'), ('Ngewa Health centre', 'Ngewa Health centre'), ('Ngoliba Health Centre', 'Ngoliba Health Centre'), ('Ngorongo Health Centre', 'Ngorongo Health Centre'), ('Nyathuna SCH', 'Nyathuna SCH'), ('Ruiru sub county Hospital', 'Ruiru sub county Hospital'), ('St.Mulumba Mission Hospital', 'St.Mulumba Mission Hospital'), ('Thika level 5 Hospital', 'Thika level 5 Hospital'), ('Thika Nursing Home', 'Thika Nursing Home'), ('Tigoni L4 Hospital', 'Tigoni L4 Hospital'), ('Uthiru Health centre', 'Uthiru Health centre'), ('Wangige SCH', 'Wangige SCH')], max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('facility_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects',
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=250)),
                ('resource', models.FileField(blank=True, null=True, upload_to='resources')),
                ('description', models.CharField(max_length=1000)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('upload_date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_counties', models.CharField(max_length=250)),
                ('counties', models.ManyToManyField(to='project.Counties')),
                ('facilities', models.ManyToManyField(to='project.Facilities')),
            ],
            options={
                'verbose_name_plural': 'sub-counties',
                'ordering': ['sub_counties'],
            },
        ),
        migrations.CreateModel(
            name='TestedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('tested_change', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=2000)),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('achievements', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.sub_counties')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_sub_counties',
            },
        ),
        migrations.AddField(
            model_name='qi_projects',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.sub_counties'),
        ),
        migrations.CreateModel(
            name='ProjectResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response_updated_date', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.projectcomments')),
                ('response_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project responses',
            },
        ),
        migrations.AddField(
            model_name='projectcomments',
            name='qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
        migrations.CreateModel(
            name='Program_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_program',
            },
        ),
        migrations.CreateModel(
            name='Hub_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('hub', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_hub',
            },
        ),
        migrations.CreateModel(
            name='County_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_counties',
            },
        ),
        migrations.CreateModel(
            name='Close_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_status_reason', models.CharField(max_length=250)),
                ('measurement_status_date', models.DateTimeField(auto_now_add=True)),
                ('limitations', models.TextField()),
                ('conclusion', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
            options={
                'verbose_name_plural': 'close_project',
            },
        ),
    ]
