# Generated by Django 3.2.5 on 2022-11-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('tested_change', models.CharField(max_length=1000)),
                ('comments', models.CharField(max_length=2000)),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('achievements', models.FloatField()),
            ],
        ),
    ]
