# Generated by Django 3.2.5 on 2023-02-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rootcauseimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RootCauseImages',
        ),
    ]
