# Generated by Django 3.2.5 on 2022-11-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_testedchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedchange',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
        migrations.AlterField(
            model_name='testedchange',
            name='achievements',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
