# Generated by Django 3.2.5 on 2022-12-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20221217_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county_qi_projects',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
        migrations.AlterField(
            model_name='hub_qi_projects',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
        migrations.AlterField(
            model_name='program_qi_projects',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
        migrations.AlterField(
            model_name='subcounty_qi_projects',
            name='project_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category'),
        ),
    ]
