# Generated by Django 3.2.5 on 2023-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qi_team_members',
            name='role',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
