# Generated by Django 3.2.5 on 2023-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20230104_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qi_team_members',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
