# Generated by Django 3.2.5 on 2023-01-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230104_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='qi_project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
            preserve_default=False,
        ),
    ]
