# Generated by Django 3.2.5 on 2022-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20221116_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Implemented', 'STARTED OR IMPLEMENTED'), ('Completed or Closed', 'COMPLETED OR CLOSED')], max_length=250),
        ),
    ]
