# Generated by Django 3.2.5 on 2022-12-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_facilities_mfl_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qi_managers',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'qi managers'},
        ),
        migrations.RenameField(
            model_name='qi_managers',
            old_name='qi_manager_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='qi_managers',
            name='second_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
