# Generated by Django 3.2.5 on 2022-11-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_qi_projects_measurement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomments',
            options={'verbose_name_plural': 'Project comments'},
        ),
        migrations.RenameField(
            model_name='projectcomments',
            old_name='project',
            new_name='qi_project',
        ),
    ]
