# Generated by Django 3.2.5 on 2022-12-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20221217_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qi_projects',
            name='facility',
        ),
    ]
