# Generated by Django 3.2.5 on 2022-11-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20221116_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomments',
            old_name='qi_project',
            new_name='qi_project_id',
        ),
    ]
