# Generated by Django 3.2.5 on 2022-11-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_qi_project_projectcomments_qi_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcomments',
            old_name='qi_project_id',
            new_name='qi_project_title',
        ),
    ]
