# Generated by Django 3.2.5 on 2022-12-17 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_remove_qi_projects_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.newuser'),
            preserve_default=False,
        ),
    ]
