# Generated by Django 3.2.5 on 2023-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_qi_team_members_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='responsibility',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='qi_team_members',
            name='role',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
