# Generated by Django 3.2.5 on 2022-11-16 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_rename_qi_project_id_projectcomments_qi_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomments',
            name='commented_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
