# Generated by Django 3.2.5 on 2023-01-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20230105_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county_qi_projects',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='county_qi_projects',
            name='responsible_people',
        ),
        migrations.RemoveField(
            model_name='hub_qi_projects',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='hub_qi_projects',
            name='responsible_people',
        ),
        migrations.RemoveField(
            model_name='program_qi_projects',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='program_qi_projects',
            name='responsible_people',
        ),
        migrations.RemoveField(
            model_name='qi_projects',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='qi_projects',
            name='responsible_people',
        ),
        migrations.RemoveField(
            model_name='subcounty_qi_projects',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='subcounty_qi_projects',
            name='responsible_people',
        ),
    ]
