# Generated by Django 3.2.5 on 2022-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_resources_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
