# Generated by Django 3.2.5 on 2023-01-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedchange',
            name='data_sources',
            field=models.CharField(default='register', max_length=250),
            preserve_default=False,
        ),
    ]
