# Generated by Django 3.2.5 on 2022-12-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_resources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='county_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
