# Generated by Django 3.2.5 on 2022-12-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_counties_county_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='qi_managers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sub_counties',
            name='sub_counties',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
