# Generated by Django 3.2.5 on 2023-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20230105_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('articles', 'articles'), ('research papers', 'research papers'), ('guides', 'guides'), ('case studies', 'case studies')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
