# Generated by Django 3.2.5 on 2022-12-02 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_projects',
            name='departments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.department'),
            preserve_default=False,
        ),
    ]
