# Generated by Django 3.2.5 on 2023-01-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_resources_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qi_team_members',
            name='responsibility',
        ),
        migrations.AlterField(
            model_name='resources',
            name='resource_type',
            field=models.CharField(choices=[('articles', 'Articles'), ('case studies', 'Case Studies'), ('guides', 'Guides'), ('research papers', 'Research Papers')], max_length=250),
        ),
        migrations.AlterField(
            model_name='testedchange',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrective_action', models.TextField()),
                ('resources_required', models.TextField()),
                ('constraints', models.TextField(blank=True, null=True)),
                ('indicator', models.CharField(max_length=250)),
                ('percent_completed', models.IntegerField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
                ('responsible', models.ManyToManyField(to='project.Qi_team_members')),
            ],
            options={
                'verbose_name_plural': 'Action plans',
            },
        ),
    ]
