# Generated by Django 3.2.5 on 2022-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_qi_projects_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qi_projects',
            name='department',
            field=models.CharField(blank=True, choices=[('Care and TX clinic', 'Care and TX clinic'), ('TB clinic', 'TB clinic'), ('Laboratory', 'Laboratory'), ('PMTCT', 'PMTCT'), ('Pharmacy', 'Pharmacy'), ('Community', 'Community'), ('VMMC', 'VMMC'), ('Nutrition clinic', 'Nutrition clinic'), ('OPD', 'OPD'), ('IPD', 'IPD')], default=0, max_length=200, null=True),
        ),
    ]
