# Generated by Django 3.2.5 on 2022-12-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_qi_managers_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qi_managers',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
