# Generated by Django 3.2.5 on 2023-01-06 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20230106_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
