# Generated by Django 3.2.5 on 2022-12-07 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0015_subcounty_qi_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='County_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_category', models.CharField(choices=[('HVL', 'HVL'), ('IPT', 'IPT'), ('Index testing', 'Index testing'), ('HTS', 'HTS'), ('TX & RETENTION', 'TX & RETENTION'), ('PMTCT', 'PMTCT'), ('MMD/MMS', 'MMD/MMS'), ('LAB', 'LAB'), ('TB', 'TB'), ('Others', 'Others')], max_length=200)),
                ('project_title', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('participants', models.TextField()),
                ('responsible_people', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('first_cycle_date', models.DateField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.counties')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_sub_counties',
            },
        ),
    ]
