# Generated by Django 3.2.5 on 2022-12-20 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_qi_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='qi_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
            preserve_default=False,
        ),
    ]
