# Generated by Django 3.2.5 on 2022-12-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_qi_team_members_qi_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qi_team_members',
            name='qi_project',
        ),
    ]
