# Generated by Django 3.2.5 on 2023-01-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_actionplan_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
