# Generated by Django 3.2.5 on 2022-12-22 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_remove_qi_team_members_qi_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_project', models.BooleanField()),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
            options={
                'verbose_name_plural': 'archived projects',
            },
        ),
    ]
