# Generated by Django 3.2.5 on 2023-01-10 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0018_alter_actionplan_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_projects',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_team_members'),
        ),
        migrations.AddField(
            model_name='qi_team_members',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
