# Generated by Django 3.2.5 on 2023-01-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20230110_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qi_team_members',
            options={'verbose_name_plural': 'qi team members'},
        ),
        migrations.RemoveField(
            model_name='qi_team_members',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qi_team_members',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='qi_team_members',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='qi_team_members',
            name='phone_number',
        ),
    ]
