# Generated by Django 3.2.5 on 2022-12-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20221214_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
    ]
