# Generated by Django 3.2.5 on 2023-01-16 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0020_auto_20230110_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Ongoing', 'STARTED OR ONGOING'), ('Completed-or-Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250),
        ),
        migrations.CreateModel(
            name='Lesson_learned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_or_opportunity', models.TextField()),
                ('goals_and_objectives', models.TextField()),
                ('results', models.TextField()),
                ('key_successes', models.TextField()),
                ('challenges', models.TextField()),
                ('best_practices', models.TextField()),
                ('recommendations', models.TextField()),
                ('resources', models.TextField()),
                ('future_plans', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
    ]
