# Generated by Django 3.2.5 on 2022-12-22 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_archiveproject_archive_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='archiveproject',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
