# Generated by Django 3.2.5 on 2022-12-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20221215_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
