# Generated by Django 3.2.5 on 2023-01-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_lesson_learned_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_learned',
            name='goals_and_objectives',
        ),
    ]
