# Generated by Django 3.2.5 on 2022-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_resources_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
