# Generated by Django 3.2.5 on 2023-01-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_lesson_learned_problem_or_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_learned',
            name='problem_or_opportunity',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
