# Generated by Django 3.2.5 on 2022-12-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_qi_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_projects',
            name='qi_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
            preserve_default=False,
        ),
    ]
