# Generated by Django 3.2.5 on 2023-01-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_lesson_learned_problem_or_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qi_projects',
            name='first_cycle_date',
        ),
    ]
