# Generated by Django 3.2.5 on 2022-12-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_qi_projects_qi_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='county_qi_projects',
            name='qi_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
        ),
        migrations.AddField(
            model_name='hub_qi_projects',
            name='qi_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
        ),
        migrations.AddField(
            model_name='program_qi_projects',
            name='qi_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
        ),
        migrations.AddField(
            model_name='subcounty_qi_projects',
            name='qi_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
        ),
        migrations.AlterField(
            model_name='qi_projects',
            name='qi_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers'),
        ),
    ]
