# Generated by Django 3.2.5 on 2023-01-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_qi_projects_first_cycle_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qi_projects',
            name='team_member',
        ),
    ]
