# Generated by Django 3.2.5 on 2023-01-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_remove_qi_projects_team_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county_qi_projects',
            name='first_cycle_date',
        ),
        migrations.RemoveField(
            model_name='hub_qi_projects',
            name='first_cycle_date',
        ),
        migrations.RemoveField(
            model_name='program_qi_projects',
            name='first_cycle_date',
        ),
        migrations.RemoveField(
            model_name='qi_projects',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='subcounty_qi_projects',
            name='first_cycle_date',
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_status', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.facilities')),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
    ]
