# Generated by Django 3.2.5 on 2023-01-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20230119_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseline',
            options={'verbose_name_plural': 'Baseline status'},
        ),
        migrations.AlterField(
            model_name='baseline',
            name='baseline_status',
            field=models.ImageField(blank=True, default='images/baseline.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.facilities'),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
    ]
