# Generated by Django 3.2.5 on 2023-01-28 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0030_auto_20230119_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qi_team_members',
            options={'ordering': ['created_by__first_name'], 'verbose_name_plural': 'qi team members'},
        ),
        migrations.AlterField(
            model_name='qi_team_members',
            name='qi_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='project.qi_projects'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.comment')),
            ],
        ),
    ]
