# Generated by Django 3.2.5 on 2023-01-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_comment_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='qi_project_title',
        ),
    ]
