# Generated by Django 3.2.5 on 2023-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='is_like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
