# Generated by Django 3.2.5 on 2023-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20230129_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='constraints',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
