# Generated by Django 3.2.5 on 2023-01-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20230130_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_projects',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.hub'),
        ),
    ]
