# Generated by Django 3.2.5 on 2023-01-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_qi_projects_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('metrics', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('communication_plan', models.TextField()),
                ('responsible_people', models.TextField()),
                ('budget', models.TextField()),
                ('risks_and_mitigation', models.TextField()),
                ('training_and_support', models.TextField()),
                ('feedback_mechanisms', models.TextField()),
                ('reaction_plan', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
    ]
