# Generated by Django 3.2.5 on 2023-01-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_qi_projects_hub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qi_projects',
            options={'ordering': ['facility_name'], 'verbose_name_plural': 'QI_Projects'},
        ),
    ]
