# Generated by Django 3.2.5 on 2023-01-30 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_sustainmentplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sustainmentplan',
            old_name='risks_and_mitigation',
            new_name='mitigation',
        ),
        migrations.AddField(
            model_name='sustainmentplan',
            name='risks',
            field=models.TextField(default=datetime.datetime(2023, 1, 30, 12, 58, 11, 644786, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
