# Generated by Django 3.2.5 on 2023-01-31 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0043_alter_qi_projects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('metrics', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('communication_plan', models.TextField()),
                ('budget', models.TextField()),
                ('risks', models.TextField()),
                ('mitigation', models.TextField()),
                ('training_and_support', models.TextField()),
                ('feedback_mechanisms', models.TextField()),
                ('reaction_plan', models.TextField()),
                ('responsible', models.TextField()),
                ('accountable', models.TextField()),
                ('consulted', models.TextField()),
                ('informed', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qi_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects')),
            ],
        ),
    ]
