# Generated by Django 3.2.5 on 2023-01-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20230130_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainmentplan',
            name='raci',
        ),
        migrations.DeleteModel(
            name='RACI',
        ),
    ]
