# Generated by Django 3.2.5 on 2023-02-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20230201_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Program_qi_projects',
        ),
    ]
