# Generated by Django 3.2.5 on 2023-01-30 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0046_auto_20230130_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountable', models.ManyToManyField(related_name='raci_accountable', to=settings.AUTH_USER_MODEL)),
                ('consulted', models.ManyToManyField(related_name='raci_consulted', to=settings.AUTH_USER_MODEL)),
                ('informed', models.ManyToManyField(related_name='raci_informed', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ManyToManyField(related_name='raci_responsible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sustainmentplan',
            name='raci',
            field=models.ManyToManyField(to='project.RACI'),
        ),
    ]
