# Generated by Django 3.2.5 on 2023-02-01 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0046_auto_20230201_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Programs',
                'ordering': ['program'],
            },
        ),
        migrations.CreateModel(
            name='Program_qi_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('settings', models.CharField(max_length=250)),
                ('problem_background', models.TextField()),
                ('process_analysis', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images')),
                ('objective', models.TextField()),
                ('numerator', models.CharField(max_length=250)),
                ('denominator', models.CharField(max_length=250)),
                ('measurement_status', models.CharField(choices=[('Started or Ongoing', 'STARTING OR ONGOING'), ('Completed or Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250)),
                ('measurement_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-annually', 'Semi-annually'), ('Annually', 'Annually')], max_length=250)),
                ('comments', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=250)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.department')),
                ('modified_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category')),
                ('qi_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_managers')),
            ],
            options={
                'verbose_name_plural': 'QI_Projects_program',
            },
        ),
    ]
