# Generated by Django 3.2.5 on 2023-02-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_program_program_qi_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_qi_projects',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.program'),
        ),
    ]
