# Generated by Django 3.2.5 on 2023-01-30 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0048_auto_20230130_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200)),
                ('responsibility', models.CharField(choices=[('R', 'Responsible'), ('A', 'Accountable'), ('C', 'Consulted'), ('I', 'Informed')], max_length=1)),
                ('newuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sustainmentplan',
            name='raci',
            field=models.ManyToManyField(to='project.RACI'),
        ),
    ]
