# Generated by Django 3.2.5 on 2023-02-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20230204_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='testedchange',
            name='program_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program_qi_projects'),
        ),
    ]
