# Generated by Django 3.2.5 on 2023-01-30 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0051_auto_20230130_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainmentplan',
            name='responsible_people',
        ),
        migrations.AddField(
            model_name='sustainmentplan',
            name='responsible',
            field=models.ManyToManyField(related_name='raci_responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
