# Generated by Django 3.2.5 on 2023-02-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_testedchange_program_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program_qi_projects'),
        ),
    ]
