# Generated by Django 3.2.5 on 2023-02-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_auto_20230204_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program'),
        ),
        migrations.AlterField(
            model_name='qi_team_members',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.facilities'),
        ),
    ]
