# Generated by Django 3.2.5 on 2023-02-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_auto_20230204_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='program_qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='project.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='qi_team_members',
            name='qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='project.qi_projects'),
        ),
    ]
