# Generated by Django 3.2.5 on 2023-02-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_auto_20230204_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionplan',
            old_name='project_qi_project',
            new_name='program_qi_project',
        ),
    ]
