# Generated by Django 3.2.5 on 2023-02-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_rename_project_qi_project_actionplan_program_qi_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='program_qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.facilities'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
    ]
