# Generated by Django 3.2.5 on 2023-02-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_auto_20230204_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='program_qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.qi_projects'),
        ),
    ]
