# Generated by Django 3.2.5 on 2023-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program_qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, default='assets/static/images/default.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, default='assets/static/images/default.png', null=True, upload_to='images'),
        ),
    ]
