# Generated by Django 3.2.5 on 2023-02-25 10:29

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cqi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qi_projects',
            name='created_by',
            field=models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
