# Generated by Django 3.2.18 on 2023-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0002_alter_resources_uploaded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseline',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Baseline status'},
        ),
        migrations.AlterModelOptions(
            name='lesson_learned',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Lesson learnt'},
        ),
        migrations.AlterModelOptions(
            name='rootcauseimages',
            options={'ordering': ['-date_created'], 'verbose_name_plural': "cqi's images status"},
        ),
        migrations.AlterField(
            model_name='baseline',
            name='baseline_status',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rootcauseimages',
            name='root_cause_image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
