# Generated by Django 3.2.5 on 2023-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0002_auto_20230220_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county_qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hub_qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='program_qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='subcounty_qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
