# Generated by Django 3.2.5 on 2023-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230220_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qi_projects',
            name='process_analysis',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
