# Generated by Django 3.2.19 on 2023-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='fyj_facilities',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
