# Generated by Django 3.2.5 on 2023-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0005_auto_20230220_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county_qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Ongoing', 'STARTING OR ONGOING'), ('Completed-or-Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250),
        ),
        migrations.AlterField(
            model_name='hub_qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Ongoing', 'STARTING OR ONGOING'), ('Completed-or-Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250),
        ),
        migrations.AlterField(
            model_name='program_qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Ongoing', 'STARTING OR ONGOING'), ('Completed-or-Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250),
        ),
        migrations.AlterField(
            model_name='subcounty_qi_projects',
            name='measurement_status',
            field=models.CharField(choices=[('Started or Ongoing', 'STARTING OR ONGOING'), ('Completed-or-Closed', 'COMPLETED OR CLOSED'), ('Canceled', 'CANCELED'), ('Not started', 'NOT STARTED'), ('Postponed', 'POSTPONED')], max_length=250),
        ),
    ]
