# Generated by Django 3.2.19 on 2023-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0006_alter_facilities_fyj_facilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='fyj_facilities',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
