# Generated by Django 3.2.5 on 2023-02-22 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0006_auto_20230222_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_learned',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='lesson_learned',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.qi_projects'),
        ),
    ]
