# Generated by Django 3.2.5 on 2023-02-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0007_auto_20230222_0654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson_learned',
            options={'verbose_name_plural': 'Lesson learnt'},
        ),
        migrations.AddField(
            model_name='sustainmentplan',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cqi.program_qi_projects'),
            preserve_default=False,
        ),
    ]
