# Generated by Django 3.2.22 on 2023-12-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0007_alter_facilities_fyj_facilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionplan',
            options={'ordering': ['qi_project', 'subcounty_qi_project', 'county_qi_project', 'hub_qi_project', 'program'], 'verbose_name_plural': 'Action plans'},
        ),
        migrations.AlterModelOptions(
            name='archiveproject',
            options={'ordering': ['qi_project', 'subcounty', 'county', 'hub', 'program'], 'verbose_name_plural': 'archived projects'},
        ),
        migrations.AlterModelOptions(
            name='baseline',
            options={'ordering': ['qi_project', 'subcounty_qi_project', 'county_qi_project__county', 'hub_qi_project__hub', 'program'], 'verbose_name_plural': 'Baseline status'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['qi_project_title', 'subcounty_qi_project_title', 'county_project_title', 'hub_qi_project_title', 'program_qi_project_title'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='county_qi_projects',
            options={'ordering': ['county'], 'verbose_name_plural': 'QI_Projects_counties'},
        ),
        migrations.AlterModelOptions(
            name='hub_qi_projects',
            options={'ordering': ['hub', 'start_date'], 'verbose_name_plural': 'QI_Projects_hub'},
        ),
        migrations.AlterModelOptions(
            name='lesson_learned',
            options={'ordering': ['project_name', 'subcounty', 'county', 'hub', 'program'], 'verbose_name_plural': 'Lesson learnt'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['facility', 'subcounty_qi_project', 'county_qi_project', 'hub_qi_project', 'program', 'start_date'], 'verbose_name_plural': 'Milestone'},
        ),
        migrations.AlterModelOptions(
            name='program_qi_projects',
            options={'ordering': ['program', 'start_date'], 'verbose_name_plural': 'QI_Projects_program'},
        ),
        migrations.AlterModelOptions(
            name='projectcomments',
            options={'ordering': ['qi_project_title'], 'verbose_name_plural': 'Project comments'},
        ),
        migrations.AlterModelOptions(
            name='projectresponses',
            options={'ordering': ['comment'], 'verbose_name_plural': 'Project responses'},
        ),
        migrations.AlterModelOptions(
            name='qi_projects',
            options={'ordering': ['facility_name', 'start_date'], 'verbose_name_plural': 'QI_Projects'},
        ),
        migrations.AlterModelOptions(
            name='rootcauseimages',
            options={'ordering': ['qi_project', 'subcounty_qi_project', 'county_qi_project', 'hub_qi_project', 'program'], 'verbose_name_plural': "cqi's images status"},
        ),
        migrations.AlterModelOptions(
            name='subcounty_qi_projects',
            options={'ordering': ['sub_county', 'start_date'], 'verbose_name_plural': 'QI_Projects_sub_counties'},
        ),
        migrations.AlterModelOptions(
            name='testedchange',
            options={'ordering': ['project', 'subcounty_project', 'county_project', 'hub_project', 'program_project'], 'verbose_name_plural': 'Test of change'},
        ),
    ]
