# Generated by Django 3.2.5 on 2023-02-22 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0008_auto_20230222_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainmentplan',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='sustainmentplan',
            name='qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.qi_projects'),
        ),
    ]
