# Generated by Django 3.2.5 on 2023-02-22 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0010_auto_20230222_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub_qi_projects',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.hub'),
        ),
    ]
