# Generated by Django 3.2.25 on 2024-09-05 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0010_auto_20240518_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('feature', 'New Feature'), ('improvement', 'Improvement'), ('bug_fix', 'Bug Fix'), ('announcement', 'Announcement')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
