# Generated by Django 3.2.25 on 2024-09-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0011_platformupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformupdate',
            name='title',
        ),
    ]
