# Generated by Django 3.2.5 on 2023-02-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0011_alter_hub_qi_projects_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveproject',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cqi.program_qi_projects'),
            preserve_default=False,
        ),
    ]
