# Generated by Django 3.2.5 on 2023-02-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0012_archiveproject_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='subcounty_qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='cqi.subcounty_qi_projects'),
        ),
    ]
