# Generated by Django 3.2.5 on 2023-02-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0013_qi_team_members_subcounty_qi_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='qi_team_members',
            name='county_qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='cqi.county_qi_projects'),
        ),
        migrations.AddField(
            model_name='qi_team_members',
            name='hub_qi_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qi_team_members', to='cqi.hub_qi_projects'),
        ),
    ]
