# Generated by Django 3.2.5 on 2023-02-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0014_auto_20230222_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='county_qi_projects',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='cqi.Trigger'),
        ),
        migrations.AddField(
            model_name='hub_qi_projects',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='cqi.Trigger'),
        ),
    ]
