# Generated by Django 3.2.5 on 2023-02-22 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0018_auto_20230222_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='close_project',
            name='county_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.county_qi_projects'),
        ),
        migrations.AlterField(
            model_name='close_project',
            name='hub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.hub_qi_projects'),
        ),
        migrations.AlterField(
            model_name='close_project',
            name='program_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.program_qi_projects'),
        ),
        migrations.AlterField(
            model_name='close_project',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.qi_projects'),
        ),
        migrations.AlterField(
            model_name='close_project',
            name='subcounty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.subcounty_qi_projects'),
        ),
    ]
