# Generated by Django 3.2.5 on 2023-02-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0019_auto_20230222_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='county_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.county_qi_projects'),
        ),
        migrations.AddField(
            model_name='comment',
            name='hub_qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.hub_qi_projects'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subcounty_qi_project_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.subcounty_qi_projects'),
        ),
    ]
