# Generated by Django 3.2.18 on 2023-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0003_alter_fyjhealthfacility_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='care_and_treatment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='county',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='datim_mfl',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='emr',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='facility',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='facility_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='health_subcounty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='hts',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='hub',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='key_pop',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='m_and_e_assistant',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='m_and_e_mentor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='mfl_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='subcounty',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='vmmc',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fyjhealthfacility',
            name='ward',
            field=models.CharField(max_length=250),
        ),
    ]
