# Generated by Django 3.2.22 on 2024-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0006_alter_fyjhealthfacility_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTKData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('mfl_code', models.IntegerField()),
                ('facility_name', models.CharField(max_length=250)),
                ('commodity_name', models.CharField(max_length=50)),
                ('beginning_balance', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('quantity_used', models.IntegerField()),
                ('quantity_requested', models.IntegerField()),
                ('tests_done', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('positive_adjustments', models.IntegerField()),
                ('negative_adjustments', models.IntegerField()),
                ('ending_balance', models.IntegerField()),
                ('days_out_of_stock', models.IntegerField()),
                ('quantity_expiring_in_6_months', models.IntegerField()),
            ],
        ),
    ]
