# Generated by Django 3.2.22 on 2024-03-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0007_rtkdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTKData',
        ),
    ]
