# Generated by Django 3.2.22 on 2024-03-07 03:00

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_analysis', '0008_delete_rtkdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTKData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('mfl_code', models.IntegerField()),
                ('facility_name', models.CharField(max_length=250)),
                ('commodity_name', models.CharField(max_length=50)),
                ('beginning_balance', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('quantity_used', models.IntegerField()),
                ('quantity_requested', models.IntegerField()),
                ('tests_done', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('positive_adjustments', models.IntegerField()),
                ('negative_adjustments', models.IntegerField()),
                ('ending_balance', models.IntegerField()),
                ('days_out_of_stock', models.IntegerField()),
                ('quantity_expiring_in_6_months', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['facility_name'],
                'unique_together': {('mfl_code', 'month')},
            },
        ),
    ]
