# Generated by Django 3.2.22 on 2024-03-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0009_rtkdata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rtkdata',
            unique_together={('mfl_code', 'month', 'commodity_name')},
        ),
    ]
