# Generated by Django 3.2.22 on 2024-03-07 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0010_alter_rtkdata_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rtkdata',
            options={'ordering': ['facility_name', 'commodity_name']},
        ),
        migrations.AddField(
            model_name='rtkdata',
            name='month_column',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
