# Generated by Django 3.2.22 on 2024-02-12 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['name'], 'verbose_name_plural': 'Journals'},
        ),
        migrations.AlterModelOptions(
            name='manuscript',
            options={'ordering': ['title', 'date_created', 'status'], 'verbose_name_plural': 'Manuscripts'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2024, 2, 12, 14, 9, 13, 296431, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='categories',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.category'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='citations',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='downloads',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='number_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'In Development'), ('submitted', 'Submitted'), ('published', 'Published')], default='draft', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='version_control',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('name',)},
        ),
    ]
