# Generated by Django 3.2.22 on 2024-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20240212_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='acceptance_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20, null=True),
        ),
    ]
