# Generated by Django 3.2.22 on 2024-02-17 09:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_manuscript_acceptance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
