# Generated by Django 3.2.22 on 2024-02-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20240217_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='methodology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
