# Generated by Django 3.2.19 on 2023-05-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyrecords',
            old_name='is_yes',
            new_name='yes_no',
        ),
    ]
