# Generated by Django 3.2.19 on 2023-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_is_yes_pharmacyrecords_yes_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='yes_no',
        ),
        migrations.AddField(
            model_name='pharmacyrecords',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyrecords',
            name='dropdown_option',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
