# Generated by Django 3.2.19 on 2023-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20230516_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='date_report_submitted',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='dropdown_option',
        ),
        migrations.AddField(
            model_name='pharmacyrecords',
            name='indicator',
            field=models.CharField(choices=[('', 'Select indicator'), ('malaria_dar', 'Is there a Malaria Commodities DAR (MoH 645) in this facility?'), ('malaria__other_registers', 'If no, what register is used to capture dispensing of Malaria commodities?'), ('malaria_dar_in_use', 'If Yes, is the Malaria Commodity DAR (MoH 645) currently in use?'), ('malaria_cdrr_report', 'Check whether the facility has a copy of the Malaria Consumption Data Report and Requisition (CDRR) (MOH743) that was prepared in the last month of the review period?'), ('date_malaria_cdrr_submitted', 'If "Yes", when was the Malaria CDRR for the last month of the review period submitted? (DD/MM/YY)'), ('arv_register_adt', 'Is there a MANUAL ARV Daily Activity Register (DAR) (MOH 367A) or an electronic dispensing tool (WebADT) in this facility? Specify which one in the comments section.'), ('arv_f_cdrr', 'Does the facility have a copy of the ARV F-CDRR (MOH 730B) that was prepared for the last month of the review period?'), ('date_arv_f_cdrr_submitted', 'If "Yes", when was the ARV F-CDRR (MOH 730B) for the last month of the review period submitted? (DD/MM/YY)'), ('arv_f_maps', 'Does the facility have a copy of the ARV F-MAPS (MOH 729B) that was prepared for the last month of the review period?'), ('date_arv_f_maps_submitted', 'If "Yes", when was the ARV F-MAPS (MOH 729B) for the last month of the review period submitted?'), ('anti_tb_register', 'Is there a DADR-Anti TB register in this facility?'), ('anti_tb_register_in_use', 'If "Yes", is the DADR-Anti TB register currently in use?'), ('anti_tb_f_cdrr', 'Does the facility have a copy of the Anti TB F-CDRR that was prepared for the last month of the review period?'), ('date_anti_tb_f_cdr_submitted', 'If "Yes", when was the Anti TB F-CDRR for the last month of the review period submitted? (DD/MM/YY)'), ('fp_register', 'Is there a Family Planning Commodities Daily Activity Register (DAR) (MOH 512) in this facility?'), ('fp_register_in_use', 'If "Yes", is the Family Planning Commodities DAR (MOH 512 or other) currently in use?'), ('fp_f_cdrr', 'Does the facility have a copy of the Family Planning Commodity Report (F-CDRR MOH 747A) that was prepared and submitted for the last month of the review period?'), ('date_fp_f_cdrr_submitted', 'If "Yes", when was the FP CDRR for the last month of the review period submitted? (DD/MM/YY)'), ('art_delivery_notes', 'Is there a file maintained with delivery notes arranged chronologically from MEDS/KEMSA for ART, separate from a file with S11s?')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
