# Generated by Django 3.2.19 on 2023-05-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20230516_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyRecords',
        ),
    ]
