# Generated by Django 3.2.19 on 2023-05-16 14:14

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dqa', '0013_auto_20230420_1439'),
        ('cqi', '0003_auto_20230426_1152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0005_delete_pharmacyrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('register_name', models.CharField(blank=True, choices=[('Malaria', 'Malaria Commodities DAR (MoH 645)'), ('ARV DAR', 'ARV Daily Activity Register (DAR) (MOH 367A)/WebADT'), ('F-MAPS', 'ARV F-MAPS (MOH 729B)'), ('DADR-Anti TB register', 'DADR-Anti TB register'), ('FP', 'Family Planning Commodities Daily Activity Register (DAR) (MOH 512)'), ('delivery notes', 'delivery notes')], max_length=100, null=True)),
                ('registers', models.TextField(blank=True, null=True)),
                ('currently_in_use', models.NullBooleanField()),
                ('last_month_copy', models.NullBooleanField()),
                ('comments', models.TextField(blank=True)),
                ('date_report_submitted', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
            ],
        ),
    ]
