# Generated by Django 3.2.19 on 2023-05-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacyrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyrecords',
            old_name='registers',
            new_name='register_available',
        ),
    ]
