# Generated by Django 3.2.19 on 2023-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_rename_registers_pharmacyrecords_register_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='currently_in_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='last_month_copy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_name',
            field=models.CharField(choices=[('Malaria', 'Malaria Commodities DAR (MoH 645)'), ('ARV DAR', 'ARV Daily Activity Register (DAR) (MOH 367A)/WebADT'), ('F-MAPS', 'ARV F-MAPS (MOH 729B)'), ('DADR-Anti TB register', 'DADR-Anti TB register'), ('FP', 'Family Planning Commodities Daily Activity Register (DAR) (MOH 512)'), ('delivery notes', 'delivery notes')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
