# Generated by Django 3.2.19 on 2023-05-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_alter_registers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyrecords',
            name='register_name',
        ),
        migrations.DeleteModel(
            name='Registers',
        ),
    ]
