# Generated by Django 3.2.19 on 2023-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_auto_20230516_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registers',
            name='register_name',
            field=models.CharField(choices=[('Malaria', 'Malaria Commodities DAR (MoH 645)'), ('ARV DAR', 'ARV Daily Activity Register (DAR) (MOH 367A)/WebADT'), ('F-MAPS', 'ARV F-MAPS (MOH 729B)'), ('DADR-Anti TB register', 'DADR-Anti TB register'), ('FP', 'Family Planning Commodities Daily Activity Register (DAR) (MOH 512)'), ('delivery notes', 'Delivery notes file')], max_length=250, unique=True),
        ),
    ]
