# Generated by Django 3.2.19 on 2023-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0014_auto_20230517_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='currently_in_use',
            field=models.CharField(choices=[('', 'Select an option'), ('1', 'Yes'), ('0', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='last_month_copy',
            field=models.CharField(choices=[('', 'Select an option'), ('1', 'Yes'), ('0', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_available',
            field=models.CharField(choices=[('', 'Select an option'), ('1', 'Yes'), ('0', 'No')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
