# Generated by Django 3.2.19 on 2023-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0017_alter_pharmacyrecords_register_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyrecords',
            name='date_of_interview',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='last_month_copy',
            field=models.CharField(choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_available',
            field=models.CharField(choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
