# Generated by Django 3.2.19 on 2023-05-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0018_auto_20230517_0919'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registers',
        ),
        migrations.AlterModelOptions(
            name='pharmacyrecords',
            options={'ordering': ['facility_name'], 'verbose_name_plural': 'PharmacyRecords'},
        ),
    ]
