# Generated by Django 3.2.19 on 2023-05-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqa', '0013_auto_20230420_1439'),
        ('cqi', '0003_auto_20230426_1152'),
        ('pharmacy', '0019_auto_20230517_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pharmacyrecords',
            unique_together={('quarter_year', 'register_name', 'facility_name', 'date_of_interview')},
        ),
    ]
