# Generated by Django 3.2.19 on 2023-05-17 07:06

import apps.pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0020_alter_pharmacyrecords_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='currently_in_use',
            field=models.CharField(blank=True, choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, validators=[apps.pharmacy.models.validate_currently_in_use]),
        ),
    ]
