# Generated by Django 3.2.19 on 2023-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0021_alter_pharmacyrecords_currently_in_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='currently_in_use',
            field=models.CharField(blank=True, choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
