# Generated by Django 3.2.19 on 2023-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_alter_pharmacyrecords_date_report_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='date_report_submitted',
            field=models.DateField(null=True),
        ),
    ]
