# Generated by Django 3.2.19 on 2023-05-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0027_workplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplan',
            options={'ordering': ['facility_name'], 'verbose_name_plural': 'Work Plan'},
        ),
        migrations.AddField(
            model_name='workplan',
            name='date_of_interview',
            field=models.DateField(blank=True, null=True),
        ),
    ]
