# Generated by Django 3.2.19 on 2023-05-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0028_auto_20230520_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkPlan',
        ),
    ]
