# Generated by Django 3.2.19 on 2023-05-22 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0031_auto_20230521_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableNames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='beginningbalance',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='expired',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='expiredunits',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='expirytracking',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='negativeadjustment',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='positiveadjustments',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='quantitydelivered',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='s11formavailability',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='s11formendorsed',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='stockcards',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='stockmanagement',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='unitissued',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='unitreceived',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='unitsupplied',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames'),
        ),
    ]
