# Generated by Django 3.2.19 on 2023-05-22 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0032_auto_20230522_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplan',
            name='stock_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stockcards', unique=True),
        ),
    ]
