# Generated by Django 3.2.19 on 2023-05-22 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0033_alter_workplan_stock_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='BeginningBalance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.beginningbalance', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='Expired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expired', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='ExpiredUnits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expiredunits', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='ExpiryTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expirytracking', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='NegativeAdjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.negativeadjustment', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='PositiveAdjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.positiveadjustments', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='QuantityDelivered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.quantitydelivered', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='S11FormAvailability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.s11formavailability', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='S11FormEndorsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.s11formendorsed', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='StockManagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stockmanagement', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='UnitIssued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.unitissued', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='UnitReceived',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.unitreceived', unique=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='UnitSupplied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.unitsupplied', unique=True),
        ),
    ]
