# Generated by Django 3.2.19 on 2023-05-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0034_auto_20230522_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplan',
            old_name='BeginningBalance',
            new_name='beginning_balance',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='Expired',
            new_name='expired',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='ExpiredUnits',
            new_name='expired_units',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='ExpiryTracking',
            new_name='expiry_tracking',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='NegativeAdjustment',
            new_name='negative_adjustment',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='PositiveAdjustments',
            new_name='positive_adjustments',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='QuantityDelivered',
            new_name='quantity_delivered',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='S11FormAvailability',
            new_name='s11_form_availability',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='S11FormEndorsed',
            new_name='s11_form_endorsed',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='StockManagement',
            new_name='stock_management',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='UnitIssued',
            new_name='unit_issued',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='UnitReceived',
            new_name='unit_received',
        ),
        migrations.RenameField(
            model_name='workplan',
            old_name='UnitSupplied',
            new_name='unit_supplied',
        ),
    ]
