# Generated by Django 3.2.19 on 2023-05-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0036_auto_20230525_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplan',
            name='unit_received',
        ),
        migrations.DeleteModel(
            name='UnitReceived',
        ),
    ]
