# Generated by Django 3.2.19 on 2023-05-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0037_auto_20230528_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplan',
            name='beginning_balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.beginningbalance'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='expired',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expired'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='expired_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expiredunits'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='expiry_tracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.expirytracking'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='negative_adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.negativeadjustment'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='positive_adjustments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.positiveadjustments'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='s11_form_availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.s11formavailability'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='s11_form_endorsed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.s11formendorsed'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='stock_cards',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stockcards'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='stock_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.stockmanagement'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='unit_issued',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.unitissued'),
        ),
        migrations.AlterField(
            model_name='workplan',
            name='unit_supplied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.unitsupplied'),
        ),
    ]
