# Generated by Django 3.2.19 on 2023-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0038_auto_20230529_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablenames',
            name='model_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
