# Generated by Django 3.2.19 on 2023-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0040_workplan_pharmacy_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
