# Generated by Django 3.2.19 on 2023-06-05 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0041_workplan_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('register_name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
            ],
        ),
    ]
