# Generated by Django 3.2.19 on 2023-06-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0042_registers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.registers'),
        ),
    ]
