# Generated by Django 3.2.19 on 2023-06-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0044_pharmacyauditteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyAuditTeam',
        ),
    ]
