# Generated by Django 3.2.19 on 2023-06-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0046_pharmacyauditteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyAuditTeam',
        ),
    ]
