# Generated by Django 3.2.19 on 2023-06-05 10:57

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0003_auto_20230426_1152'),
        ('dqa', '0013_auto_20230420_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0047_delete_pharmacyauditteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyAuditTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pharmacy_carder', models.CharField(max_length=255)),
                ('pharmacy_organization', models.CharField(max_length=255)),
                ('module', models.CharField(default='Pharmacy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
            ],
        ),
    ]
