# Generated by Django 3.2.19 on 2023-06-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0049_alter_pharmacyauditteam_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplan',
            name='pharmacy_records',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyrecords'),
        ),
    ]
