# Generated by Django 3.2.25 on 2024-11-19 10:03

import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cqi', '0012_remove_platformupdate_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dqa', '0022_auto_20240623_1737'),
        ('pharmacy', '0052_auto_20240729_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_of_interview', models.DateField(blank=True, null=True)),
                ('register_available', models.CharField(choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=10)),
                ('last_month_copy', models.CharField(choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
                ('register_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.registers')),
            ],
            options={
                'verbose_name_plural': 'Delivery Notes',
                'ordering': ['facility_name'],
                'unique_together': {('quarter_year', 'register_name', 'facility_name', 'date_of_interview')},
            },
        ),
    ]
