# Generated by Django 3.2.25 on 2024-11-20 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0054_auto_20241120_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expired',
            name='al_6',
        ),
        migrations.RemoveField(
            model_name='expired',
            name='dmpa_im',
        ),
        migrations.RemoveField(
            model_name='expired',
            name='dmpa_sc',
        ),
        migrations.RemoveField(
            model_name='expired',
            name='family_planning_rod2',
        ),
        migrations.RemoveField(
            model_name='expirytracking',
            name='al_6',
        ),
        migrations.RemoveField(
            model_name='expirytracking',
            name='dmpa_im',
        ),
        migrations.RemoveField(
            model_name='expirytracking',
            name='dmpa_sc',
        ),
        migrations.RemoveField(
            model_name='expirytracking',
            name='family_planning_rod2',
        ),
        migrations.RemoveField(
            model_name='s11formavailability',
            name='al_6',
        ),
        migrations.RemoveField(
            model_name='s11formavailability',
            name='dmpa_im',
        ),
        migrations.RemoveField(
            model_name='s11formavailability',
            name='dmpa_sc',
        ),
        migrations.RemoveField(
            model_name='s11formavailability',
            name='family_planning_rod2',
        ),
        migrations.RemoveField(
            model_name='stockcards',
            name='al_6',
        ),
        migrations.RemoveField(
            model_name='stockcards',
            name='dmpa_im',
        ),
        migrations.RemoveField(
            model_name='stockcards',
            name='dmpa_sc',
        ),
        migrations.RemoveField(
            model_name='stockcards',
            name='family_planning_rod2',
        ),
    ]
