# Generated by Django 3.2.25 on 2024-11-21 04:22

import apps.pharmacy.models
import crum
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dqa', '0022_auto_20240623_1737'),
        ('cqi', '0012_remove_platformupdate_title'),
        ('pharmacy', '0059_auto_20241121_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyMalariaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_of_interview', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('al_24', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('al_6', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('model_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
            ],
            options={
                'verbose_name_plural': 'Anti-Malaria',
                'ordering': ['facility_name'],
                'unique_together': {('quarter_year', 'description', 'facility_name', 'date_of_interview')},
            },
        ),
        migrations.CreateModel(
            name='PharmacyFpModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_of_interview', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('family_planning_rod', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('family_planning_rod2', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('dmpa_im', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('dmpa_sc', models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cqi.facilities')),
                ('model_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.tablenames')),
                ('modified_by', models.ForeignKey(blank=True, default=crum.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quarter_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dqa.period')),
            ],
            options={
                'verbose_name_plural': 'Family planning',
                'ordering': ['facility_name'],
                'unique_together': {('quarter_year', 'description', 'facility_name', 'date_of_interview')},
            },
        ),
    ]
