# Generated by Django 3.2.25 on 2024-11-30 05:53

import apps.pharmacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0061_auto_20241121_0834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacyfpqualitativemodel',
            options={'ordering': ['facility_name'], 'verbose_name_plural': 'Family planning Qualitative'},
        ),
        migrations.AlterModelOptions(
            name='pharmacymalariaqualitativemodel',
            options={'ordering': ['facility_name'], 'verbose_name_plural': 'Anti-Malaria Qualitative'},
        ),
        migrations.AddField(
            model_name='beginningbalance',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='beginningbalance',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='expired',
            name='pead_arv_dtg_50mg',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='expired',
            name='r_inh',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='expiredunits',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='expiredunits',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='expirytracking',
            name='pead_arv_dtg_50mg',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='expirytracking',
            name='r_inh',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='negativeadjustment',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='negativeadjustment',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='positiveadjustments',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='positiveadjustments',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='s11formavailability',
            name='pead_arv_dtg_50mg',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='s11formavailability',
            name='r_inh',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='s11formendorsed',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='s11formendorsed',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='stockcards',
            name='pead_arv_dtg_50mg',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='stockcards',
            name='r_inh',
            field=models.CharField(choices=[('', '-'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=4),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='stockmanagement',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='unitissued',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='unitissued',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='unitsupplied',
            name='pead_arv_dtg_50mg',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
        migrations.AddField(
            model_name='unitsupplied',
            name='r_inh',
            field=models.IntegerField(default=0, validators=[apps.pharmacy.models.validate_non_negative]),
        ),
    ]
