# Generated by Django 3.2.25 on 2025-01-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0063_auto_20241130_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='last_month_copy',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacyrecords',
            name='register_available',
            field=models.CharField(blank=True, choices=[('', 'Select an option'), ('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10, null=True),
        ),
    ]
